"""
ystocker.daily_email
~~~~~~~~~~~~~~~~~~~~
The daily markets email: the subscriber broadcast after the US close and the
one-off "Send" on /daily. Pure -- data in, strings out -- so every layout choice
here is testable without an app, a network or SES (tests/test_daily_email.py).

It replaced a builder in routes.py that laid the mail out 1,200px wide, set the
two AI commentaries in side-by-side table cells -- which cannot reflow, so on a
phone each became a column about 180px wide -- inserted the commentary
unescaped, with any Markdown as literal asterisks, dated the Chinese edition
"September 30, 2026", named sectors and events in English in it, and signed
every mail yStocker whatever site the reader had subscribed on. The content is
unchanged: the two short prose commentaries from /api/daily-summary, and the
day's tables.

Rules, each for a client that breaks without it:

* **640px, one column, tables for layout.** Outlook's Word engine supports
  neither flex nor float, and a phone cannot reflow table cells set side by
  side, so every block is a full-width row, stacked.
* **Inline styles only.** Gmail drops a <style> block. The palette and the mark
  are report_email.py's, so the two mails this site sends read as one sender's.
* **The commentary is escaped Markdown.** report_email.render() is the
  email-safe port of static/markdown.js: text is escaped before any tag is
  added, and **bold** arrives bold.
* **Dark, and it says so.** ``color-scheme: dark`` keeps Apple Mail from
  inverting a mail that is already dark into a washed-out light one.
* **Linked to the reader's own site.** A subscriber's site is recorded when they
  subscribe (site_for_host); the brand and every link follow it.
"""
from __future__ import annotations

import os
import re
from datetime import date
from html import escape
from typing import Any, Iterable, Optional

from ystocker import report_email as _mail

# report_email's palette, plus the two inks this mail's figures need.
_BG, _CARD, _LINE = _mail._BG, _mail._CARD, _mail._LINE
_TEXT, _BRIGHT, _DIM, _ACCENT = _mail._TEXT, _mail._BRIGHT, _mail._DIM, _mail._ACCENT
_SANS = _mail._SANS
_UP, _DOWN = "#34d399", "#f87171"
_ROW = "#2b3a52"          # the rule between table rows: one step up from the card

TA_SITE = "https://trade-agents.com"
YS_SITE = "https://stock.li-family.us"

_MONTHS_EN = ("January", "February", "March", "April", "May", "June", "July",
              "August", "September", "October", "November", "December")
_WEEKDAYS_EN = ("Monday", "Tuesday", "Wednesday", "Thursday", "Friday",
                "Saturday", "Sunday")
_WEEKDAYS_ZH = ("星期一", "星期二", "星期三", "星期四", "星期五", "星期六", "星期日")

_T: dict[str, dict[str, str]] = {
    "en": {
        "title": "Daily Markets Report",
        "us": "US Market Commentary",
        "cn": "CN / Asia Commentary",
        "read_web": "Read the full report on the web →",
        "read_web_note": "Both long-form reports, the charts and the rest of today's data.",
        "indices": "Indices", "index": "Index", "last": "Last", "day": "Day",
        "week": "Week",
        "metrics": "Sentiment & Volatility", "indicator": "Indicator",
        "reading": "Reading", "note": "",
        "vix": "VIX", "pcr": "Put/Call ratio", "pcr_ma": "20-day avg {v}",
        "fg": "Fear & Greed", "aaii_bull": "AAII bullish", "aaii_bear": "AAII bearish",
        "aaii_spread": "Bull–bear spread",
        "sectors": "Sectors", "sector": "Sector",
        "commodities": "Commodity Ratios", "commodity": "", "value": "Value",
        "gold": "Gold", "silver": "Silver", "gs": "Gold / Silver", "gc": "Gold / Copper",
        "events": "Economic Events", "when": "When", "event": "Event", "impact": "Impact",
        "gainers": "Top Gainers", "losers": "Top Losers", "stock": "Stock", "price": "Price",
        "footer": ("Generated by {brand} from Yahoo Finance, CBOE and Federal Reserve "
                   "data. For research only — not investment advice."),
        "unsubscribe": "Unsubscribe from daily reports",
        "one_off": "You received this as a one-time send.",
    },
    "zh": {
        "title": "每日市场报告",
        "us": "美股市场解读",
        "cn": "中国 / 亚洲市场解读",
        "read_web": "在网页上阅读完整报告 →",
        "read_web_note": "两份长篇报告、图表，以及今天的其余数据。",
        "indices": "指数", "index": "指数", "last": "最新", "day": "今日",
        "week": "本周",
        "metrics": "情绪与波动", "indicator": "指标", "reading": "读数", "note": "",
        "vix": "VIX 波动率", "pcr": "看跌/看涨比", "pcr_ma": "20日均值 {v}",
        "fg": "恐惧与贪婪", "aaii_bull": "AAII 看多", "aaii_bear": "AAII 看空",
        "aaii_spread": "牛熊差",
        "sectors": "板块表现", "sector": "板块",
        "commodities": "商品比率", "commodity": "", "value": "数值",
        "gold": "黄金", "silver": "白银", "gs": "金银比", "gc": "金铜比",
        "events": "经济事件", "when": "时间", "event": "事件", "impact": "影响",
        "gainers": "涨幅榜", "losers": "跌幅榜", "stock": "股票", "price": "价格",
        "footer": ("本报告由 {brand} 自动生成，数据来自 Yahoo Finance、CBOE 及美联储。"
                   "仅供研究使用，不构成投资建议。"),
        "unsubscribe": "退订每日报告",
        "one_off": "此邮件为一次性发送。",
    },
}

# The indices /api/markets carries, in the order a reader scans them.
_INDICES = (("spx", "S&P 500", "标普500"), ("ixic", "Nasdaq", "纳斯达克"),
            ("dji", "Dow Jones", "道琼斯"), ("ftse", "FTSE 100", "富时100"),
            ("n225", "Nikkei 225", "日经225"), ("sse", "Shanghai", "上证指数"),
            ("csi500", "CSI 500", "中证500"), ("twii", "Taiwan", "台湾加权"),
            ("kospi", "KOSPI", "韩国综合"))

# /api/markets' sector labels. The page reads markets.sector.* from i18n.js,
# which has no entry for the last two; a mail cannot read i18n.js at all.
_SECTORS_ZH = {
    "Tech": "科技", "Financials": "金融", "Energy": "能源", "Healthcare": "医疗健康",
    "Industrials": "工业", "Consumer Disc.": "非必需消费", "Consumer Stap.": "必需消费",
    "Utilities": "公用事业", "Materials": "材料", "Real Estate": "房地产",
    "Comm.": "通信服务", "Telecom": "电信",
}
_FG_ZH = {"extreme fear": "极度恐惧", "fear": "恐惧", "neutral": "中性",
          "greed": "贪婪", "extreme greed": "极度贪婪"}
_IMPACT = {"High": ("High", "高", _DOWN), "Medium": ("Medium", "中", "#fbbf24"),
           "Low": ("Low", "低", _DIM)}
_COUNTRY_ZH = {
    "United States": "美国", "US": "美国", "China": "中国", "Japan": "日本",
    "Euro Area": "欧元区", "Eurozone": "欧元区", "EU": "欧元区",
    "United Kingdom": "英国", "UK": "英国", "Germany": "德国", "France": "法国",
    "Canada": "加拿大", "Australia": "澳大利亚", "South Korea": "韩国", "Korea": "韩国",
    "Taiwan": "台湾", "India": "印度", "Brazil": "巴西", "Switzerland": "瑞士",
    "New Zealand": "新西兰", "Hong Kong": "香港", "Mexico": "墨西哥",
    "Italy": "意大利", "Spain": "西班牙", "Netherlands": "荷兰", "Sweden": "瑞典",
    "Norway": "挪威", "Singapore": "新加坡", "Indonesia": "印度尼西亚",
    "South Africa": "南非", "Turkey": "土耳其", "Russia": "俄罗斯",
}


def _t(lang: str, key: str) -> str:
    return _T["zh" if lang == "zh" else "en"][key]


def _esc(value: Any) -> str:
    return escape("" if value is None else str(value), quote=True)


# ---------------------------------------------------------------------------
# Where a mail links, and whose name it carries
# ---------------------------------------------------------------------------

def site_for_host(host: Optional[str]) -> str:
    """The site a request came in on, as the base a mail's links use.

    trade-agents.com's two names are one site; any other host is itself, over
    https (nginx terminates TLS, so Flask never sees the scheme). "" for a local
    host, which no reader's mail should ever link to.
    """
    h = (host or "").split(":")[0].strip().lower()
    if not h or h in ("localhost", "127.0.0.1", "0.0.0.0"):
        return ""
    try:
        from ystocker import TA_HOSTS
    except Exception:  # noqa: BLE001 - never fail a mail over branding
        TA_HOSTS = {"trade-agents.com", "www.trade-agents.com"}
    return TA_SITE if h in TA_HOSTS else f"https://{h}"


def default_site() -> str:
    """The site for a subscriber with none recorded -- everyone who subscribed
    before sites were: APP_BASE_URL if set, else yStocker's host. The fallback
    it replaces, ystocker.com, is not a domain this box serves, so an
    unsubscribe link built on it could not have worked."""
    return (os.environ.get("APP_BASE_URL") or YS_SITE).rstrip("/")


def brand(site: str) -> str:
    """TradeAgents or yStocker, by the site the mail links to (report_email's
    rule, so the two mails cannot disagree about one host)."""
    return _mail.brand_for(site)


def day_label(today_iso: str, lang: str, weekday: bool = False) -> str:
    """"September 30, 2026" / "2026年9月30日", optionally with the weekday."""
    try:
        d = date.fromisoformat(today_iso)
    except (TypeError, ValueError):
        return str(today_iso or "")
    if lang == "zh":
        text = f"{d.year}年{d.month}月{d.day}日"
        return f"{text} {_WEEKDAYS_ZH[d.weekday()]}" if weekday else text
    text = f"{_MONTHS_EN[d.month - 1]} {d.day}, {d.year}"
    return f"{_WEEKDAYS_EN[d.weekday()]}, {text}" if weekday else text


def daily_url(site: str, lang: str) -> str:
    return f"{site}/daily?lang={'zh' if lang == 'zh' else 'en'}"


# ---------------------------------------------------------------------------
# Pieces
# ---------------------------------------------------------------------------

def _num(value: Any, spec: str) -> Optional[str]:
    try:
        return format(float(value), spec)
    except (TypeError, ValueError):
        return None


def _chg(value: Any, dec: int = 2, unit: str = "%") -> str:
    """A signed change in the up/down ink; zero in neither, and a dash for none."""
    try:
        x = float(value)
    except (TypeError, ValueError):
        return f'<span style="color:{_DIM}">—</span>'
    colour = _UP if x > 0 else _DOWN if x < 0 else _DIM
    return f'<span style="color:{colour}">{"+" if x > 0 else ""}{x:.{dec}f}{unit}</span>'


_TH = (f"padding:0 10px 8px;font-size:11px;font-weight:700;letter-spacing:.06em;"
       f"text-transform:uppercase;color:{_DIM};border-bottom:1px solid {_LINE}")
_TD = f"padding:9px 10px;font-size:14px;line-height:1.4;color:{_TEXT};border-bottom:1px solid {_ROW}"


def _table(cols: list[tuple[str, str]], rows: list[list[str]]) -> str:
    """A full-width data table. ``cols`` is (label, "left"|"right"); a cell is
    HTML the caller has already escaped. The first column is the row's name,
    set bright; right-aligned columns are figures, set in tabular numerals and
    never broken across lines."""
    head = "".join(f'<th align="{a}" style="{_TH};text-align:{a}">{_esc(label)}</th>'
                   for label, a in cols)
    body = []
    for i, row in enumerate(rows):
        cells = []
        for j, (cell, (_, align)) in enumerate(zip(row, cols)):
            style = _TD
            if i == len(rows) - 1:
                style += ";border-bottom:0"
            if j == 0:
                style += f";color:{_BRIGHT};font-weight:600"
            if align == "right":
                style += ";text-align:right;white-space:nowrap;font-variant-numeric:tabular-nums"
            cells.append(f'<td align="{align}" valign="top" style="{style}">{cell}</td>')
        body.append("<tr>" + "".join(cells) + "</tr>")
    return ('<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" '
            f'style="border-collapse:collapse;width:100%"><tr>{head}</tr>{"".join(body)}</table>')


def _section(label: str, inner: str) -> str:
    """One block of the mail: a label in the accent ink, then its content."""
    return (f'<tr><td style="padding:26px 24px 0">'
            f'<div style="margin:0 0 12px;font-size:12px;font-weight:700;letter-spacing:.08em;'
            f'text-transform:uppercase;color:{_ACCENT}">{_esc(label)}</div>{inner}</td></tr>')


def _button(href: str, label: str) -> str:
    """A button that renders everywhere: a coloured table cell around a link,
    since Outlook ignores padding on an <a>."""
    return ('<table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr>'
            f'<td bgcolor="#f1f5f9" style="border-radius:8px;background:#f1f5f9">'
            f'<a href="{_esc(href)}" style="display:inline-block;padding:11px 18px;'
            f'font-size:14px;font-weight:600;line-height:1.2;color:{_BG};text-decoration:none;'
            f'border-radius:8px">{_esc(label)}</a></td></tr></table>')


def _header(brand_name: str, lang: str, today_iso: str, site: str) -> str:
    """The masthead: report_email's mark and wordmark, then what this is and when.
    A two-cell table, since Outlook's Word engine supports neither flex nor float."""
    return (
        '<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr>'
        f'<td width="44" valign="top" style="width:44px;padding:0 14px 0 0">{_mail._logo()}</td>'
        '<td valign="middle">'
        f'<div style="margin:0 0 2px;font-size:21px;font-weight:700;letter-spacing:-.01em;line-height:1.2">'
        f'<a href="{_esc(site)}" style="color:#ffffff;text-decoration:none">{_esc(brand_name)}</a></div>'
        f'<div style="color:#bfdbfe;font-size:14px;line-height:1.4">{_esc(_t(lang, "title"))}</div>'
        f'<div style="margin:2px 0 0;color:#93c5fd;font-size:12px;line-height:1.5">'
        f'{_esc(day_label(today_iso, lang, weekday=True))}</div>'
        '</td></tr></table>')


# ---------------------------------------------------------------------------
# Sections
# ---------------------------------------------------------------------------

def _commentary(label: str, text: str) -> str:
    return _section(label, _mail.render(text)) if (text or "").strip() else ""


def _indices(indices: dict, lang: str) -> str:
    rows = []
    for key, en, zh in _INDICES:
        d = (indices or {}).get(key) or {}
        last = _num(d.get("current"), ",.2f")
        if last is None:
            continue
        rows.append([_esc(zh if lang == "zh" else en), last, _chg(d.get("day_chg"))])
    if not rows:
        return ""
    return _section(_t(lang, "indices"), _table(
        [(_t(lang, "index"), "left"), (_t(lang, "last"), "right"), (_t(lang, "day"), "right")], rows))


def _metrics(vix: dict, sentiment: dict, lang: str) -> str:
    fg = (sentiment or {}).get("fg") or {}
    pcr = (sentiment or {}).get("pcr") or {}
    aaii = (sentiment or {}).get("aaii") or {}
    dim = f'<span style="color:{_DIM};font-size:13px">{{}}</span>'
    rows = []
    v = _num((vix or {}).get("current"), ".2f")
    if v is not None:
        rows.append([_esc(_t(lang, "vix")), v, _chg((vix or {}).get("day_chg"))])
    v = _num(pcr.get("current"), ".2f")
    if v is not None:
        ma = _num(pcr.get("ma20"), ".2f")
        rows.append([_esc(_t(lang, "pcr")), v,
                     dim.format(_esc(_t(lang, "pcr_ma").format(v=ma))) if ma else ""])
    v = _num(fg.get("score"), ".0f")
    if v is not None:
        rating = str(fg.get("rating") or "")
        if lang == "zh":
            rating = _FG_ZH.get(rating.strip().lower(), rating)
        rows.append([_esc(_t(lang, "fg")), v, dim.format(_esc(rating))])
    v = _num(aaii.get("bullish"), ".1f")
    if v is not None:
        rows.append([_esc(_t(lang, "aaii_bull")), f"{v}%", ""])
    v = _num(aaii.get("bearish"), ".1f")
    if v is not None:
        rows.append([_esc(_t(lang, "aaii_bear")), f"{v}%", ""])
    if aaii.get("bull_bear_spread") is not None:
        rows.append([_esc(_t(lang, "aaii_spread")), _chg(aaii.get("bull_bear_spread"), 1), ""])
    if not rows:
        return ""
    return _section(_t(lang, "metrics"), _table(
        [(_t(lang, "indicator"), "left"), (_t(lang, "reading"), "right"), (_t(lang, "note"), "right")],
        rows))


def _sectors(sectors: list, lang: str) -> str:
    ranked = sorted((s for s in (sectors or []) if s.get("label")),
                    key=lambda s: s.get("day_chg") if s.get("day_chg") is not None else -999,
                    reverse=True)
    if not ranked:
        return ""
    weekly = any(s.get("week_chg_pct") is not None for s in ranked)
    cols = [(_t(lang, "sector"), "left"), (_t(lang, "day"), "right")]
    if weekly:
        cols.append((_t(lang, "week"), "right"))
    rows = []
    for s in ranked:
        label = s["label"]
        name = _SECTORS_ZH.get(label, label) if lang == "zh" else label
        row = [_esc(name), _chg(s.get("day_chg"))]
        if weekly:
            row.append(_chg(s.get("week_chg_pct"), 1))
        rows.append(row)
    return _section(_t(lang, "sectors"), _table(cols, rows))


def _commodities(gold: dict, lang: str) -> str:
    g = gold or {}
    rows = []
    v = _num(g.get("gold_price"), ",.0f")
    if v is not None:
        rows.append([_esc(_t(lang, "gold")), f"${v}", ""])
    v = _num(g.get("silver_price"), ",.2f")
    if v is not None:
        rows.append([_esc(_t(lang, "silver")), f"${v}", ""])
    v = _num(g.get("current_gs"), ".1f")
    if v is not None:
        rows.append([_esc(_t(lang, "gs")), v, _chg(g.get("gs_day_chg"))])
    v = _num(g.get("current_gc"), ".1f")
    if v is not None:
        rows.append([_esc(_t(lang, "gc")), v, _chg(g.get("gc_day_chg"))])
    if not rows:
        return ""
    return _section(_t(lang, "commodities"), _table(
        [(_t(lang, "commodity"), "left"), (_t(lang, "value"), "right"), (_t(lang, "day"), "right")],
        rows))


def _events(events: list, today_iso: str, lang: str) -> str:
    """The next high-impact events -- or, on a quiet calendar, the next ones."""
    upcoming = [e for e in (events or []) if (e.get("date") or "") >= (today_iso or "")]
    shown = [e for e in upcoming if e.get("impact") == "High"][:8] or upcoming[:8]
    rows = []
    for e in shown:
        when = (e.get("date") or "")[5:]
        if e.get("time"):
            when = f"{when} {e['time']}".strip()
        name = (e.get("zh") if lang == "zh" and e.get("zh") else e.get("event")) or ""
        country = e.get("country") or ""
        if lang == "zh":
            country = _COUNTRY_ZH.get(country, country)
        cell = _esc(name)
        if country:
            cell = f'<span style="color:{_DIM}">{_esc(country)}</span> · {cell}'
        en, zh, colour = _IMPACT.get(e.get("impact") or "", (e.get("impact") or "", e.get("impact") or "", _DIM))
        impact = f'<span style="color:{colour};font-weight:600">{_esc(zh if lang == "zh" else en)}</span>'
        rows.append([f'<span style="font-weight:500">{_esc(when)}</span>', cell, impact])
    if not rows:
        return ""
    return _section(_t(lang, "events"), _table(
        [(_t(lang, "when"), "left"), (_t(lang, "event"), "left"), (_t(lang, "impact"), "right")], rows))


def _movers(movers: list, label_key: str, lang: str) -> str:
    rows = []
    for m in movers or []:
        ticker = m.get("ticker") or ""
        if not ticker:
            continue
        name = (m.get("name") or "")[:40]
        cell = _esc(ticker)
        if name:
            cell += (f'<br><span style="color:{_DIM};font-size:12px;font-weight:400">'
                     f'{_esc(name)}</span>')
        price = _num(m.get("price"), ",.2f")
        rows.append([cell, f"${price}" if price else "—", _chg(m.get("day_chg"))])
    if not rows:
        return ""
    return _section(_t(lang, label_key), _table(
        [(_t(lang, "stock"), "left"), (_t(lang, "price"), "right"), (_t(lang, "day"), "right")], rows))


# ---------------------------------------------------------------------------
# The mail
# ---------------------------------------------------------------------------

def build(lang: str, site: str, *, summary_us: str = "", summary_cn: str = "",
          indices: Optional[dict] = None, sectors: Optional[list] = None,
          vix: Optional[dict] = None, gold: Optional[dict] = None,
          sentiment: Optional[dict] = None, events: Optional[list] = None,
          gainers: Optional[list] = None, losers: Optional[list] = None,
          today_iso: str = "") -> dict[str, str]:
    """One mail: ``{"subject", "html_tmpl", "text_base"}``.

    ``html_tmpl`` still holds ``__UNSUB__``, which the sender fills per
    recipient -- the one part of the mail that differs between two readers of
    the same site and language.
    """
    lang = "zh" if lang == "zh" else "en"
    site = (site or default_site()).rstrip("/")
    name = brand(site)
    today_iso = today_iso or date.today().isoformat()
    web = daily_url(site, lang)
    subject = f"{name} {_t(lang, 'title')} — {day_label(today_iso, lang)}"

    commentary = _commentary(_t(lang, "us"), summary_us) + _commentary(_t(lang, "cn"), summary_cn)
    cta = (f'<tr><td style="padding:24px 24px 0">{_button(web, _t(lang, "read_web"))}'
           f'<div style="margin:8px 0 0;color:{_DIM};font-size:12px;line-height:1.5">'
           f'{_esc(_t(lang, "read_web_note"))}</div></td></tr>')
    data = "".join([
        _indices(indices or {}, lang), _metrics(vix or {}, sentiment or {}, lang),
        _sectors(sectors or [], lang), _commodities(gold or {}, lang),
        _events(events or [], today_iso, lang),
        _movers(gainers or [], "gainers", lang), _movers(losers or [], "losers", lang),
    ])
    # The line an inbox shows beside the subject: the commentary's first words,
    # rather than whatever text the mail happens to open with. Plain text, so
    # Markdown's markers go -- "**情绪**" is what the inbox would print.
    preheader = _mail._plain(re.sub(r"[*_`#>|~]+", "", summary_us or summary_cn or ""), 140)

    footer = _esc(_t(lang, "footer").format(brand=name))
    html_tmpl = f"""<!DOCTYPE html>
<html lang="{'zh-CN' if lang == 'zh' else 'en'}"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="color-scheme" content="dark"><meta name="supported-color-schemes" content="dark">
<title>{_esc(subject)}</title></head>
<body style="margin:0;padding:0;background:{_BG};font-family:{_SANS}">
<div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent">{_esc(preheader)}</div>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:{_BG}">
  <tr><td align="center" style="padding:24px 8px">
    <table role="presentation" width="640" cellpadding="0" cellspacing="0" border="0"
           style="width:100%;max-width:640px;background:{_CARD};border-radius:14px">
      <tr><td style="padding:24px 24px 20px;border-bottom:1px solid {_LINE}">{_header(name, lang, today_iso, site)}</td></tr>
      {commentary}{cta}{data}
      <tr><td style="padding:28px 24px 0"><div style="height:1px;background:{_LINE};line-height:1px;font-size:0">&nbsp;</div></td></tr>
      <tr><td style="padding:16px 24px 26px">
        <p style="margin:0;color:{_DIM};font-size:12px;line-height:1.6">{footer}</p>
        <p style="margin:6px 0 0;font-size:12px;line-height:1.6"><a href="{_esc(web)}" style="color:{_ACCENT};text-decoration:underline">{_esc(web.split('?')[0].replace('https://', ''))}</a></p>
        <p style="margin:6px 0 0">__UNSUB__</p>
      </td></tr>
    </table>
  </td></tr>
</table>
</body></html>"""

    text = [subject, f"{_t(lang, 'read_web').rstrip(' →')}: {web}", ""]
    for key, body in (("us", summary_us), ("cn", summary_cn)):
        if (body or "").strip():
            text += [f"=== {_t(lang, key)} ===", "", body.strip(), ""]
    for key, en, zh in _INDICES:
        d = (indices or {}).get(key) or {}
        last = _num(d.get("current"), ",.2f")
        if last is not None:
            chg = _num(d.get("day_chg"), "+.2f")
            text.append(f"{zh if lang == 'zh' else en}: {last}" + (f"  {chg}%" if chg else ""))
    text += ["", _t(lang, "footer").format(brand=name)]
    return {"subject": subject, "html_tmpl": html_tmpl, "text_base": "\n".join(text)}


def build_all(sites: Iterable[str], summaries_us: dict, summaries_cn: dict, *,
              fallback_lang: str = "en", **data: Any) -> dict[tuple[str, str], dict[str, str]]:
    """Every mail a send needs: ``{(site, lang): mail}`` for each site and both
    languages. A language with no commentary of its own borrows
    ``fallback_lang``'s, as the old builder did, rather than going out without."""
    out = {}
    for site in {(s or default_site()).rstrip("/") for s in sites} or {default_site()}:
        for lang in ("en", "zh"):
            out[(site, lang)] = build(
                lang, site,
                summary_us=summaries_us.get(lang) or summaries_us.get(fallback_lang, ""),
                summary_cn=summaries_cn.get(lang) or summaries_cn.get(fallback_lang, ""),
                **data)
    return out


def unsubscribe(site: str, token: str, lang: str) -> tuple[str, str]:
    """The per-reader line: (html, text). A one-off send carries no token."""
    if token:
        url = f"{(site or default_site()).rstrip('/')}/unsubscribe?token={token}"
        label = _t(lang, "unsubscribe")
        return (f'<a href="{_esc(url)}" style="color:{_DIM};font-size:11px;'
                f'text-decoration:underline">{_esc(label)}</a>', f"{label}: {url}")
    note = _t(lang, "one_off")
    return f'<span style="color:{_DIM};font-size:11px">{_esc(note)}</span>', note


def send_all(ses_client, recipients: Iterable[dict], mails: dict[tuple[str, str], dict[str, str]],
             ses_from: str) -> tuple[int, list[str]]:
    """Send each recipient the mail for their site and language, with their own
    unsubscribe line. Returns (sent, failed addresses); a failure is logged and
    skipped, never raised, so one bad address cannot stop the broadcast.

    ``ses_client`` is passed in -- boto3's in production, a fake in the tests.
    """
    import logging

    log = logging.getLogger(__name__)
    sent, errors = 0, []
    for rec in recipients:
        lang = "zh" if rec.get("lang") == "zh" else "en"
        site = (rec.get("site") or default_site()).rstrip("/")
        mail = mails.get((site, lang)) or mails.get((site, "en")) or next(iter(mails.values()))
        unsub_html, unsub_text = unsubscribe(site, rec.get("token", ""), lang)
        try:
            ses_client.send_email(
                Source=ses_from,
                Destination={"ToAddresses": [rec["email"]]},
                Message={
                    "Subject": {"Data": mail["subject"], "Charset": "UTF-8"},
                    "Body": {
                        "Html": {"Data": mail["html_tmpl"].replace("__UNSUB__", unsub_html),
                                 "Charset": "UTF-8"},
                        "Text": {"Data": f"{mail['text_base']}\n{unsub_text}", "Charset": "UTF-8"},
                    },
                },
            )
            sent += 1
            log.info("Daily report sent to %s (lang=%s site=%s)", rec["email"], lang, site)
        except Exception as exc:  # noqa: BLE001 - one address must not stop the rest
            log.warning("SES send failed for %s: %s", rec["email"], exc)
            errors.append(rec["email"])
    return sent, errors
