"""
yplanter.plants_db
~~~~~~~~~~~~~~~~~~
Curated database of plants, vegetables, and yard suggestions
for Seattle / Pacific Northwest (USDA Zone 8b).
"""
from __future__ import annotations

# ─── Seattle / PNW Vegetables & Herbs ────────────────────────────────────────

VEGETABLES: list[dict] = [
    {
        "id": "tomato",
        "name": "Tomatoes",
        "emoji": "\U0001f345",
        "category": "vegetable",
        "varieties": ["Early Girl", "Sungold Cherry", "Stupice", "Black Krim", "Oregon Spring"],
        "pnw_notes": "Short-season varieties do best in Seattle. Start indoors Feb\u2013Mar, transplant after last frost (mid-Apr). Use black plastic mulch to warm soil.",
        "sun": "Full sun (8+ hrs)",
        "water": "1\u20132 inches/week, consistent",
        "soil": "Rich, well-drained, pH 6.0\u20136.8",
        "start_indoors": "Feb\u2013Mar",
        "transplant": "Mid Apr\u2013May",
        "direct_sow": None,
        "harvest": "Jul\u2013Oct",
        "spacing_in": 24,
        "difficulty": "moderate",
        "frost_hardy": False,
        "tip": "Sungold cherry tomatoes are bulletproof in Seattle. Pinch suckers for larger fruit on indeterminate types.",
        "companions": ["Basil", "Carrots", "Marigolds"],
        "avoid_near": ["Brassicas", "Fennel"],
    },
    {
        "id": "kale",
        "name": "Kale",
        "emoji": "\U0001f96c",
        "category": "vegetable",
        "varieties": ["Lacinato (Dinosaur)", "Red Russian", "Winterbor", "Dwarf Blue Curled"],
        "pnw_notes": "A PNW superstar. Can grow nearly year-round in Seattle. Sweeter after frost. Start in spring or late summer for fall/winter harvest.",
        "sun": "Full sun to part shade",
        "water": "1 inch/week",
        "soil": "Rich, well-drained, pH 6.0\u20137.0",
        "start_indoors": "Feb\u2013Mar (spring crop)",
        "transplant": "Mar\u2013Apr or Jul\u2013Aug",
        "direct_sow": "Mar\u2013Aug",
        "harvest": "Year-round (with protection)",
        "spacing_in": 18,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Lacinato kale is the Seattle gardener's best friend\u2014harvest outer leaves and it keeps producing for months.",
        "companions": ["Beets", "Celery", "Onions", "Potatoes"],
        "avoid_near": ["Strawberries"],
    },
    {
        "id": "lettuce",
        "name": "Lettuce & Salad Greens",
        "emoji": "\U0001f96c",
        "category": "vegetable",
        "varieties": ["Buttercrunch", "Red Sails", "Mesclun Mix", "Little Gem", "Winter Density"],
        "pnw_notes": "Thrives in Seattle's cool, mild climate. Direct sow early spring through fall. Bolts in summer heat\u2014plant in shade then.",
        "sun": "Part shade to full sun",
        "water": "Consistent moisture",
        "soil": "Loose, well-drained, pH 6.0\u20137.0",
        "start_indoors": None,
        "transplant": None,
        "direct_sow": "Mar\u2013Sep (succession plant every 2\u20133 weeks)",
        "harvest": "Apr\u2013Nov",
        "spacing_in": 8,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Succession sow every 2\u20133 weeks for continuous harvest. In summer, plant on the north side of taller crops for shade.",
        "companions": ["Carrots", "Radishes", "Strawberries"],
        "avoid_near": [],
    },
    {
        "id": "sugar-snap-peas",
        "name": "Sugar Snap Peas",
        "emoji": "\U0001f95c",
        "category": "vegetable",
        "varieties": ["Sugar Snap", "Cascadia", "Super Sugar Snap"],
        "pnw_notes": "A PNW spring classic. One of the earliest crops you can direct sow. Peas fix nitrogen in the soil for future crops.",
        "sun": "Full sun to part shade",
        "water": "Moderate, even moisture",
        "soil": "Well-drained, pH 6.0\u20137.5",
        "start_indoors": None,
        "transplant": None,
        "direct_sow": "Feb\u2013Mar (as soon as soil is workable)",
        "harvest": "May\u2013Jul",
        "spacing_in": 3,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Inoculate seeds with rhizobium bacteria for better nitrogen fixation. Provide a trellis for climbing types.",
        "companions": ["Carrots", "Radishes", "Spinach", "Corn"],
        "avoid_near": ["Onions", "Garlic"],
    },
    {
        "id": "zucchini",
        "name": "Zucchini & Summer Squash",
        "emoji": "\U0001f952",
        "category": "vegetable",
        "varieties": ["Black Beauty", "Costata Romanesco", "Gold Rush Yellow", "Pattypan"],
        "pnw_notes": "Very productive in Seattle summers. One or two plants can feed a family. Start indoors or direct sow after frost danger.",
        "sun": "Full sun (6+ hrs)",
        "water": "1\u20132 inches/week at base",
        "soil": "Rich, well-drained, pH 6.0\u20137.5",
        "start_indoors": "Apr",
        "transplant": "May",
        "direct_sow": "May\u2013Jun",
        "harvest": "Jul\u2013Oct",
        "spacing_in": 36,
        "difficulty": "easy",
        "frost_hardy": False,
        "tip": "Harvest when 6\u20138 inches for best flavor. Check daily\u2014they grow FAST. Hand-pollinate if bees are scarce early season.",
        "companions": ["Corn", "Beans", "Nasturtiums"],
        "avoid_near": ["Potatoes"],
    },
    {
        "id": "garlic",
        "name": "Garlic",
        "emoji": "\U0001f9c4",
        "category": "vegetable",
        "varieties": ["Music (hardneck)", "Chesnok Red", "Inchelium Red (softneck)", "Georgian Crystal"],
        "pnw_notes": "Plant in October for harvest next July. PNW is one of the best garlic-growing regions in the US. Hardneck types produce delicious scapes in spring.",
        "sun": "Full sun",
        "water": "Moderate\u2014reduce before harvest",
        "soil": "Loose, well-drained, pH 6.0\u20137.0",
        "start_indoors": None,
        "transplant": None,
        "direct_sow": "Oct\u2013Nov (fall planting)",
        "harvest": "Jul (following year)",
        "spacing_in": 6,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Snap off scapes in spring to redirect energy to bulbs. Cure for 2\u20134 weeks in a dry, shaded area before storing.",
        "companions": ["Tomatoes", "Roses", "Fruit trees"],
        "avoid_near": ["Beans", "Peas"],
    },
    {
        "id": "blueberries",
        "name": "Blueberries",
        "emoji": "\U0001fad0",
        "category": "fruit",
        "varieties": ["Duke (early)", "Bluecrop (mid)", "Elliott (late)", "Sunshine Blue (compact)"],
        "pnw_notes": "The PNW is blueberry country\u2014Washington is the #1 US producer. Acidic native soil is naturally perfect. Plant 2+ varieties for cross-pollination.",
        "sun": "Full sun",
        "water": "1\u20132 inches/week, consistent",
        "soil": "Acidic (pH 4.5\u20135.5), amended with peat/sulfur",
        "start_indoors": None,
        "transplant": "Early spring (bare root) or anytime (potted)",
        "direct_sow": None,
        "harvest": "Jun\u2013Sep",
        "spacing_in": 60,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Net bushes when berries ripen\u2014birds love them too. Mulch heavily with acidic material (pine bark, coffee grounds).",
        "companions": ["Rhododendrons", "Azaleas", "Strawberries"],
        "avoid_near": [],
    },
    {
        "id": "strawberries",
        "name": "Strawberries",
        "emoji": "\U0001f353",
        "category": "fruit",
        "varieties": ["Hood", "Totem", "Rainier", "Seascape (everbearing)", "Alpine"],
        "pnw_notes": "Hood strawberries are legendary in the PNW for their intense flavor. Plant in spring. Everbearing types fruit spring through fall.",
        "sun": "Full sun (6+ hrs)",
        "water": "1 inch/week, consistent",
        "soil": "Rich, well-drained, slightly acidic pH 5.5\u20136.5",
        "start_indoors": None,
        "transplant": "Mar\u2013Apr",
        "direct_sow": None,
        "harvest": "Jun (June-bearing) or Jun\u2013Oct (everbearing)",
        "spacing_in": 18,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Mulch with straw to keep berries clean. Pinch first-year flowers on June-bearers for a bigger second-year crop.",
        "companions": ["Borage", "Lettuce", "Spinach", "Beans"],
        "avoid_near": ["Brassicas", "Fennel"],
    },
    {
        "id": "herbs-basil",
        "name": "Basil",
        "emoji": "\U0001f33f",
        "category": "herb",
        "varieties": ["Genovese", "Thai", "Purple", "Lemon", "African Blue"],
        "pnw_notes": "Needs warmth\u2014start indoors and transplant after last frost. Grow against south-facing wall or use black mulch for extra warmth.",
        "sun": "Full sun (6+ hrs)",
        "water": "Moderate, consistent",
        "soil": "Rich, well-drained, pH 6.0\u20137.0",
        "start_indoors": "Mar\u2013Apr",
        "transplant": "May\u2013Jun",
        "direct_sow": None,
        "harvest": "Jun\u2013Oct",
        "spacing_in": 12,
        "difficulty": "moderate",
        "frost_hardy": False,
        "tip": "Pinch flower buds to extend harvest. Make pesto batches and freeze in ice cube trays for winter.",
        "companions": ["Tomatoes", "Peppers"],
        "avoid_near": ["Sage", "Rue"],
    },
    {
        "id": "herbs-rosemary",
        "name": "Rosemary",
        "emoji": "\U0001f33f",
        "category": "herb",
        "varieties": ["Arp (hardiest)", "Tuscan Blue", "Prostrate/Trailing", "Miss Jessup"],
        "pnw_notes": "Perennial in Seattle\u2014once established, it thrives with minimal care. Arp variety is the hardiest for PNW winters.",
        "sun": "Full sun",
        "water": "Low\u2014drought tolerant once established",
        "soil": "Sandy, well-drained, pH 6.0\u20137.0",
        "start_indoors": None,
        "transplant": "Spring",
        "direct_sow": None,
        "harvest": "Year-round",
        "spacing_in": 24,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Plant by a sunny wall for extra warmth and drainage. Excellent in containers on patios.",
        "companions": ["Sage", "Thyme", "Lavender"],
        "avoid_near": [],
    },
    {
        "id": "beans-green",
        "name": "Green Beans",
        "emoji": "\U0001f33f",
        "category": "vegetable",
        "varieties": ["Provider (bush)", "Blue Lake (bush/pole)", "Kentucky Wonder (pole)", "Scarlet Runner"],
        "pnw_notes": "Direct sow after soil warms to 60\u00b0F. Bush types are quicker to harvest; pole types produce longer.",
        "sun": "Full sun (6+ hrs)",
        "water": "1 inch/week",
        "soil": "Well-drained, pH 6.0\u20137.0",
        "start_indoors": None,
        "transplant": None,
        "direct_sow": "May\u2013Jun (after soil warms to 60\u00b0F)",
        "harvest": "Jul\u2013Oct",
        "spacing_in": 4,
        "difficulty": "easy",
        "frost_hardy": False,
        "tip": "Pick frequently to keep plants producing. Scarlet Runner beans have gorgeous flowers that attract hummingbirds.",
        "companions": ["Corn", "Squash", "Cucumbers"],
        "avoid_near": ["Onions", "Garlic"],
    },
    {
        "id": "carrots",
        "name": "Carrots",
        "emoji": "\U0001f955",
        "category": "vegetable",
        "varieties": ["Nantes (Bolero)", "Danvers", "Scarlet Nantes", "Purple Haze", "Little Finger"],
        "pnw_notes": "Thrive in PNW's cool weather. Direct sow spring through mid-summer. Can overwinter in the ground with mulch for winter harvest.",
        "sun": "Full sun to part shade",
        "water": "Consistent moisture for even growth",
        "soil": "Loose, sandy, rock-free, pH 6.0\u20136.8",
        "start_indoors": None,
        "transplant": None,
        "direct_sow": "Mar\u2013Jul",
        "harvest": "Jun\u2013Dec (can overwinter)",
        "spacing_in": 3,
        "difficulty": "moderate",
        "frost_hardy": True,
        "tip": "Sow seeds on the surface and barely cover. Mix with radish seeds as row markers. Thin ruthlessly for straight roots.",
        "companions": ["Peas", "Lettuce", "Tomatoes", "Onions"],
        "avoid_near": ["Dill"],
    },
    {
        "id": "potatoes",
        "name": "Potatoes",
        "emoji": "\U0001f954",
        "category": "vegetable",
        "varieties": ["Yukon Gold", "Red Pontiac", "Fingerling", "Purple Majesty", "All Blue"],
        "pnw_notes": "Plant seed potatoes in March\u2013April. Hill soil around stems as they grow. Easy and rewarding\u2014great for kids!",
        "sun": "Full sun (6+ hrs)",
        "water": "Consistent, 1\u20132 inches/week",
        "soil": "Loose, well-drained, slightly acidic pH 5.0\u20136.0",
        "start_indoors": None,
        "transplant": None,
        "direct_sow": "Mar\u2013Apr",
        "harvest": "Jul\u2013Sep",
        "spacing_in": 12,
        "difficulty": "easy",
        "frost_hardy": False,
        "tip": "Grow in raised beds or bags for easy harvest. Don't wash before storing\u2014brush off soil and cure in dark for 2 weeks.",
        "companions": ["Beans", "Corn", "Horseradish"],
        "avoid_near": ["Tomatoes", "Squash"],
    },
    {
        "id": "beets",
        "name": "Beets",
        "emoji": "\U0001f534",
        "category": "vegetable",
        "varieties": ["Detroit Dark Red", "Chioggia (candy stripe)", "Golden", "Bull's Blood"],
        "pnw_notes": "Cool-weather crop perfect for PNW. Direct sow spring and late summer for fall harvest. Greens are edible and nutritious too!",
        "sun": "Full sun to part shade",
        "water": "Consistent moisture",
        "soil": "Loose, well-drained, pH 6.0\u20137.0",
        "start_indoors": None,
        "transplant": None,
        "direct_sow": "Mar\u2013Jul",
        "harvest": "May\u2013Nov",
        "spacing_in": 4,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Each beet 'seed' is actually a cluster\u2014thin to one seedling per cluster. Roast Chioggia beets for stunning candy-striped rounds.",
        "companions": ["Onions", "Lettuce", "Cabbage"],
        "avoid_near": ["Pole beans"],
    },
    {
        "id": "cucumber",
        "name": "Cucumbers",
        "emoji": "\U0001f952",
        "category": "vegetable",
        "varieties": ["Marketmore 76", "Lemon Cucumber", "Diva", "Suyo Long", "Tasty Jade"],
        "pnw_notes": "Need warm soil\u2014start indoors or wait until late May to direct sow. Use a trellis for straighter fruit and better air circulation.",
        "sun": "Full sun (6+ hrs)",
        "water": "1\u20132 inches/week, consistent",
        "soil": "Rich, well-drained, pH 6.0\u20137.0",
        "start_indoors": "Apr",
        "transplant": "Late May\u2013Jun",
        "direct_sow": "Late May\u2013Jun",
        "harvest": "Jul\u2013Sep",
        "spacing_in": 18,
        "difficulty": "moderate",
        "frost_hardy": False,
        "tip": "Pick cucumbers when young for crispest texture. Lemon cucumbers are a fun PNW heirloom\u2014round, yellow, and mild.",
        "companions": ["Beans", "Peas", "Sunflowers"],
        "avoid_near": ["Potatoes", "Aromatic herbs"],
    },
    {
        "id": "chard",
        "name": "Swiss Chard",
        "emoji": "\U0001f308",
        "category": "vegetable",
        "varieties": ["Bright Lights", "Fordhook Giant", "Ruby Red", "Peppermint"],
        "pnw_notes": "Almost as hardy as kale in Seattle. Beautiful ornamental AND edible. Tolerates light frost and partial shade.",
        "sun": "Full sun to part shade",
        "water": "1 inch/week",
        "soil": "Rich, well-drained, pH 6.0\u20137.0",
        "start_indoors": None,
        "transplant": None,
        "direct_sow": "Apr\u2013Aug",
        "harvest": "Jun\u2013Nov",
        "spacing_in": 12,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Bright Lights variety has stunning rainbow stems\u2014doubles as edible landscaping. Harvest outer leaves for continuous production.",
        "companions": ["Beans", "Cabbage", "Onions"],
        "avoid_near": [],
    },
]


# ─── Indoor Houseplants for PNW ──────────────────────────────────────────────

HOUSEPLANTS: list[dict] = [
    {
        "id": "monstera-deliciosa",
        "name": "Monstera Deliciosa",
        "emoji": "\U0001f331",
        "category": "houseplant",
        "difficulty": "easy",
        "light": "Bright indirect light",
        "water": "Every 1\u20132 weeks when top 2\" dry",
        "humidity": "40\u201360%",
        "temp": "60\u201385\u00b0F",
        "pnw_notes": "Loves PNW's humid winters. Place near a bright window but out of direct sun. Growth slows Nov\u2013Feb with shorter days.",
        "toxic_pets": True,
        "tip": "Provide a moss pole for larger leaves. Clean leaves monthly\u2014Seattle dust is real.",
    },
    {
        "id": "pothos-golden",
        "name": "Golden Pothos",
        "emoji": "\U0001f33f",
        "category": "houseplant",
        "difficulty": "easy",
        "light": "Low to bright indirect",
        "water": "Every 1\u20132 weeks, let dry between",
        "humidity": "Any",
        "temp": "60\u201385\u00b0F",
        "pnw_notes": "Perfect for Seattle's dark winter months\u2014one of few plants that thrives in low light. Great for north-facing apartments.",
        "toxic_pets": True,
        "tip": "Trim leggy vines and root cuttings in water for new plants.",
    },
    {
        "id": "snake-plant",
        "name": "Snake Plant",
        "emoji": "\U0001fab4",
        "category": "houseplant",
        "difficulty": "easy",
        "light": "Low to bright\u2014very adaptable",
        "water": "Every 2\u20134 weeks",
        "humidity": "Any",
        "temp": "55\u201385\u00b0F",
        "pnw_notes": "Nearly indestructible. Releases oxygen at night\u2014great for PNW bedrooms. Water less in winter.",
        "toxic_pets": True,
        "tip": "Reduce watering to once monthly in Seattle's dark, cool winters.",
    },
    {
        "id": "fiddle-leaf-fig",
        "name": "Fiddle Leaf Fig",
        "emoji": "\U0001f332",
        "category": "houseplant",
        "difficulty": "hard",
        "light": "Bright indirect, some morning sun",
        "water": "Weekly when top 1\" dry",
        "humidity": "50\u201365%",
        "temp": "60\u201380\u00b0F",
        "pnw_notes": "Challenging in Seattle\u2014needs a bright south-facing window and consistent routine. Consider a grow light Nov\u2013Feb.",
        "toxic_pets": True,
        "tip": "Don't move it. FLFs hate changes. Wipe leaves monthly and rotate quarterly.",
    },
    {
        "id": "ferns",
        "name": "Ferns (Boston, Maidenhair)",
        "emoji": "\U0001f33f",
        "category": "houseplant",
        "difficulty": "moderate",
        "light": "Medium indirect",
        "water": "Keep consistently moist",
        "humidity": "60%+",
        "temp": "55\u201375\u00b0F",
        "pnw_notes": "PNW's naturally humid air helps! Bathrooms are ideal. Seattle's cool temps suit ferns perfectly.",
        "toxic_pets": False,
        "tip": "Native sword ferns grow wild in WA forests\u2014proof that ferns love PNW climate.",
    },
    {
        "id": "peace-lily",
        "name": "Peace Lily",
        "emoji": "\U0001f33c",
        "category": "houseplant",
        "difficulty": "easy",
        "light": "Low to medium indirect",
        "water": "Weekly, droops when thirsty",
        "humidity": "50%+",
        "temp": "60\u201380\u00b0F",
        "pnw_notes": "Excellent for Seattle's overcast days. Filters indoor air. Blooms white flowers even in low light.",
        "toxic_pets": True,
        "tip": "Use filtered water\u2014Seattle tap water is good but some areas have fluoride that causes brown tips.",
    },
    {
        "id": "pilea",
        "name": "Chinese Money Plant",
        "emoji": "\U0001f4b2",
        "category": "houseplant",
        "difficulty": "easy",
        "light": "Bright indirect",
        "water": "Weekly when top inch dry",
        "humidity": "Average",
        "temp": "55\u201380\u00b0F",
        "pnw_notes": "Produces lots of pups for sharing\u2014a favorite at Seattle plant swaps. Rotate for even growth.",
        "toxic_pets": False,
        "tip": "Popular at PNW plant swaps and Facebook Marketplace. Share the babies!",
    },
    {
        "id": "calathea",
        "name": "Calathea / Prayer Plant",
        "emoji": "\U0001f3a8",
        "category": "houseplant",
        "difficulty": "hard",
        "light": "Medium indirect, no direct sun",
        "water": "Keep lightly moist, filtered water only",
        "humidity": "60%+",
        "temp": "62\u201380\u00b0F",
        "pnw_notes": "PNW humidity helps but winter heating dries air\u2014use a humidifier. Stunning leaf patterns worth the effort.",
        "toxic_pets": False,
        "tip": "Group with other humidity-loving plants to create a microclimate.",
    },
]


# ─── PNW Yard & Garden Suggestions ──────────────────────────────────────────

YARD_SUGGESTIONS: list[dict] = [
    {
        "id": "native-garden",
        "title": "PNW Native Plant Garden",
        "emoji": "\U0001f33b",
        "description": "Create a low-maintenance garden with native Pacific Northwest plants that support local pollinators and wildlife.",
        "plants": [
            {"name": "Oregon Grape (Mahonia)", "notes": "WA state flower. Evergreen, shade-tolerant, yellow flowers \u2192 blue berries."},
            {"name": "Sword Fern", "notes": "The quintessential PNW understory fern. Thrives in shade."},
            {"name": "Salal", "notes": "Evergreen groundcover. Edible berries. Extremely low-maintenance."},
            {"name": "Red-flowering Currant", "notes": "First native shrub to bloom (Mar). Hummingbird magnet."},
            {"name": "Pacific Madrone", "notes": "Beautiful peeling bark, evergreen broadleaf. Iconic PNW tree."},
            {"name": "Western Red Cedar", "notes": "Evergreen screen/hedge. Sacred to Coast Salish peoples."},
            {"name": "Nootka Rose", "notes": "Native wild rose. Pink flowers, rose hips for tea."},
        ],
        "benefits": ["Low water once established", "Supports native bees & butterflies", "Year-round interest", "No fertilizer needed"],
        "tip": "Shop at local native plant sales (WA Native Plant Society) for best prices and locally-sourced genetics.",
    },
    {
        "id": "rain-garden",
        "title": "Rain Garden",
        "emoji": "\U0001f327\ufe0f",
        "description": "Manage Seattle's abundant rainfall naturally. A rain garden captures runoff from roofs/driveways, filtering pollutants before they reach Puget Sound.",
        "plants": [
            {"name": "Red Twig Dogwood", "notes": "Stunning red branches in winter. Tolerates wet feet."},
            {"name": "Blue Flag Iris", "notes": "Moisture-loving perennial. Purple flowers spring/summer."},
            {"name": "Sedges (Carex)", "notes": "Native grass-like plants. Perfect for rain garden edges."},
            {"name": "Joe Pye Weed", "notes": "Tall, late-summer blooms. Butterfly favorite."},
            {"name": "Rush (Juncus)", "notes": "Tolerates standing water. Great for center of rain garden."},
        ],
        "benefits": ["Reduces stormwater runoff 30\u201399%", "Filters pollutants naturally", "Seattle offers rebates", "Attracts dragonflies & pollinators"],
        "tip": "Seattle Public Utilities offers free rain garden coaching and up to $4.50/sq ft in rebates through RainWise.",
    },
    {
        "id": "edible-landscape",
        "title": "Edible Landscaping",
        "emoji": "\U0001f34e",
        "description": "Replace ornamental plants with beautiful edibles. Seattle's mild climate supports an incredible range of edible perennials.",
        "plants": [
            {"name": "Blueberry Hedge", "notes": "Replace boxwood with blueberries\u2014fall color + fruit!"},
            {"name": "Espaliered Apple/Pear", "notes": "Flat-trained fruit trees along fences. Space-efficient."},
            {"name": "Kiwi Vine (Hardy)", "notes": "Covers arbors. Grape-sized fuzzy fruits."},
            {"name": "Herb Border", "notes": "Rosemary, thyme, lavender\u2014fragrant, evergreen, edible."},
            {"name": "Rhubarb", "notes": "Dramatic ornamental leaves + spring harvest. Perennial."},
            {"name": "Fig Tree (Desert King)", "notes": "Seattle-hardy variety. Plant against south wall."},
        ],
        "benefits": ["Free food from your yard!", "More interesting than lawn", "Lower maintenance than grass", "Teaches kids where food comes from"],
        "tip": "Join Seattle's City Fruit for free fruit tree pruning workshops and to connect with other urban orchardists.",
    },
    {
        "id": "pollinator-garden",
        "title": "Pollinator Garden",
        "emoji": "\U0001f41d",
        "description": "Support bees, butterflies, and hummingbirds with a sequence of blooms from February through October.",
        "plants": [
            {"name": "Crocus (Feb\u2013Mar)", "notes": "First food for emerging bumblebees."},
            {"name": "Lavender (Jun\u2013Aug)", "notes": "Bee paradise. English types hardiest in PNW."},
            {"name": "Echinacea (Jul\u2013Sep)", "notes": "Butterflies and seed-eating birds love it."},
            {"name": "Aster (Sep\u2013Oct)", "notes": "Critical late-season nectar source."},
            {"name": "Red Hot Poker (Jul\u2013Sep)", "notes": "Hummingbird magnet. Striking orange spikes."},
            {"name": "Bee Balm (Jul\u2013Aug)", "notes": "Attracts both bees and hummingbirds."},
        ],
        "benefits": ["Supports declining pollinator populations", "Beautiful successive blooms", "Many are perennial (plant once)", "Helps your veggie garden via pollination"],
        "tip": "Leave some bare soil patches\u201470% of native bee species are ground-nesters and need exposed earth.",
    },
    {
        "id": "raised-beds",
        "title": "Raised Bed Vegetable Garden",
        "emoji": "\U0001f3d7\ufe0f",
        "description": "Raised beds solve Seattle's common soil issues (clay, poor drainage) and warm up earlier in spring for a longer growing season.",
        "plants": [
            {"name": "Spring: Peas, Lettuce, Radishes", "notes": "Start as early as February in raised beds."},
            {"name": "Summer: Tomatoes, Beans, Squash", "notes": "Warm soil = better warm-crop yields."},
            {"name": "Fall: Kale, Beets, Carrots", "notes": "Extend the season with row cover."},
            {"name": "Winter: Garlic, Overwintering Onions", "notes": "Soil stays workable in raised beds."},
        ],
        "benefits": ["Better drainage than Seattle clay", "Soil warms 2\u20133 weeks earlier", "Easier on knees and backs", "Better pest control"],
        "tip": "Use untreated cedar (PNW native wood, rot-resistant). Fill with 60% topsoil + 30% compost + 10% pumice. Seattle's Cedar Grove compost is excellent.",
    },
    {
        "id": "japanese-garden",
        "title": "PNW Japanese-Inspired Garden",
        "emoji": "\U0001f3ef",
        "description": "Seattle's climate is remarkably similar to Japan's. Many traditional Japanese garden plants thrive here naturally.",
        "plants": [
            {"name": "Japanese Maple (Acer palmatum)", "notes": "Hundreds of varieties. Stunning fall color."},
            {"name": "Azaleas & Rhododendrons", "notes": "WA state flower (rhodo). Acidic PNW soil = perfect."},
            {"name": "Bamboo (Clumping varieties)", "notes": "Fargesia types are non-invasive. Avoid running bamboo!"},
            {"name": "Moss", "notes": "Grows naturally in PNW shade. Embrace it instead of fighting it."},
            {"name": "Japanese Forest Grass", "notes": "Golden cascading grass. Elegant in shade."},
            {"name": "Camellia", "notes": "Winter blooms when nothing else flowers. Evergreen."},
        ],
        "benefits": ["Naturally suited to PNW climate", "Year-round visual interest", "Peaceful, meditative spaces", "Low maintenance once established"],
        "tip": "Visit the Seattle Japanese Garden in the Arboretum for inspiration\u2014it's one of the finest outside Japan.",
    },
]


# ─── Seattle Planting Calendar (Zone 8b) ────────────────────────────────────

PLANTING_CALENDAR: list[dict] = [
    {"month": "January", "emoji": "\u2744\ufe0f", "tasks": [
        "Plan your garden\u2014order seeds from Territorial Seed Co (Cottage Grove, OR) or Uprising Seeds (Bellingham, WA)",
        "Prune dormant fruit trees and roses",
        "Start onion seeds indoors under grow lights",
        "Clean and sharpen tools",
    ]},
    {"month": "February", "emoji": "\U0001f331", "tasks": [
        "Direct sow: peas, fava beans, spinach, radishes (if soil is workable)",
        "Start indoors: tomatoes, peppers, eggplant",
        "Prune blueberries and grapes",
        "Apply dormant spray to fruit trees",
        "Top-dress beds with compost",
    ]},
    {"month": "March", "emoji": "\U0001f337", "tasks": [
        "Direct sow: lettuce, carrots, beets, chard, kale, potatoes",
        "Transplant: broccoli, cabbage, cauliflower starts",
        "Start basil and cucumbers indoors",
        "Divide perennials",
        "Plant bare-root fruit trees, berries, and roses",
    ]},
    {"month": "April", "emoji": "\U0001f327\ufe0f", "tasks": [
        "Transplant tomato and pepper starts (after mid-month, with protection)",
        "Direct sow: beans (after soil reaches 60\u00b0F), more lettuce and greens",
        "Start squash and cucumber seeds indoors",
        "Plant strawberries",
        "Apply organic slug bait (slugs are a PNW reality)",
    ]},
    {"month": "May", "emoji": "\u2600\ufe0f", "tasks": [
        "After last frost (~May 10): transplant tomatoes, peppers, squash, basil",
        "Direct sow: beans, corn, cucumbers, summer squash",
        "Mulch everything to conserve moisture",
        "Set up drip irrigation if possible",
        "Harden off seedlings before transplanting",
    ]},
    {"month": "June", "emoji": "\U0001f33b", "tasks": [
        "Succession plant: lettuce, beans, beets",
        "Harvest: peas, lettuce, radishes, strawberries",
        "Side-dress tomatoes with compost or fish emulsion",
        "Stake/cage tomatoes before they flop",
        "Watch for aphids\u2014blast with water or introduce ladybugs",
    ]},
    {"month": "July", "emoji": "\U0001f345", "tasks": [
        "Harvest: first tomatoes, beans, zucchini, blueberries, cucumbers",
        "Plant fall crops: kale, broccoli, cabbage starts",
        "Direct sow: fall beets, carrots, lettuce for fall",
        "Water consistently\u2014Seattle's dry summers surprise newcomers!",
        "Harvest garlic when lower leaves brown",
    ]},
    {"month": "August", "emoji": "\U0001f33e", "tasks": [
        "Peak harvest: tomatoes, squash, beans, corn, berries",
        "Direct sow: overwintering crops (kale, spinach, chard)",
        "Plant fall lettuce in succession",
        "Start saving seeds from best performers",
        "Enjoy the bounty! Preserve excess via canning, freezing, or sharing",
    ]},
    {"month": "September", "emoji": "\U0001f342", "tasks": [
        "Harvest winter squash when stems are dry and corky",
        "Plant garlic (mid-Sep through Oct in PNW)",
        "Sow cover crops (crimson clover, winter rye) in empty beds",
        "Transplant fall starts: overwintering broccoli, cauliflower",
        "Begin putting garden to bed\u2014pull spent plants, compost",
    ]},
    {"month": "October", "emoji": "\U0001f383", "tasks": [
        "Plant garlic cloves (top priority for PNW fall gardening!)",
        "Plant spring-blooming bulbs (tulips, daffodils, crocus)",
        "Mulch overwintering crops heavily",
        "Clean up fallen leaves\u2014compost or use as mulch",
        "Plant trees, shrubs, and perennials (fall is ideal in PNW)",
    ]},
    {"month": "November", "emoji": "\U0001f343", "tasks": [
        "Harvest: kale, chard, leeks, Brussels sprouts (sweeter after frost!)",
        "Protect tender plants with row cover or cold frames",
        "Rake and compost leaves\u2014or mulch beds with leaf mold",
        "Clean and store tools, drain hoses",
        "Order seed catalogs and start dreaming about next year",
    ]},
    {"month": "December", "emoji": "\U0001f384", "tasks": [
        "Harvest overwintered greens as needed",
        "Plan next year's garden layout (rotate crops!)",
        "Browse seed catalogs: Territorial, Uprising, Adaptive Seeds, Nichols Garden",
        "Give gardening gifts: seeds, tools, garden journal",
        "Rest and compost\u2014the garden is sleeping",
    ]},
]


# ─── Useful Resources ────────────────────────────────────────────────────────

RESOURCES: list[dict] = [
    {"name": "Territorial Seed Company", "url": "https://territorialseed.com", "desc": "PNW-focused seed company based in Oregon. Varieties selected for our climate."},
    {"name": "Uprising Seeds", "url": "https://uprisingorganics.com", "desc": "Organic seeds from Bellingham, WA. Open-pollinated varieties bred for PNW."},
    {"name": "Swansons Nursery", "url": "https://swansonsnursery.com", "desc": "Seattle institution since 1924. Expert staff and PNW-adapted plants."},
    {"name": "Seattle Tilth Alliance", "url": "https://tilthalliance.org", "desc": "Community gardens, classes, and the annual Edible Plant Sale (May)."},
    {"name": "WSU Extension \u2013 King County", "url": "https://extension.wsu.edu/king/", "desc": "Free research-based gardening advice. Master Gardener hotline."},
    {"name": "RainWise (Seattle)", "url": "https://700milliongallons.org", "desc": "Rebates for rain gardens and cisterns. Up to $4.50/sq ft."},
    {"name": "City Fruit", "url": "https://cityfruit.org", "desc": "Urban fruit tree education, pruning workshops, and community harvest."},
    {"name": "WA Native Plant Society", "url": "https://wnps.org", "desc": "Native plant sales, events, and habitat restoration info."},
    {"name": "The Sill", "url": "https://thesill.com", "desc": "Houseplant care guides, articles, and online plant shop."},
    {"name": "Gardenize", "url": "https://gardenize.com", "desc": "Plant diary app. Track watering, fertilizing, and growth photos."},
    {"name": "Seedtime", "url": "https://seedtime.us", "desc": "Free garden planning tool with zone-based planting calendars."},
]


# ─── Search / Filter Helpers ─────────────────────────────────────────────────

ALL_PLANTS = VEGETABLES + HOUSEPLANTS
CATEGORIES = {"vegetable": "Vegetables", "fruit": "Fruit", "herb": "Herbs", "houseplant": "Houseplants"}
DIFFICULTIES = ["easy", "moderate", "hard"]

# Wikipedia article names for fetching thumbnail images (client-side)
# and YouTube search queries for growing guides
_MEDIA: dict[str, dict] = {
    "tomato":             {"wiki": "Tomato",               "yt": "how to grow tomatoes seattle pacific northwest"},
    "kale":               {"wiki": "Kale",                 "yt": "how to grow kale pacific northwest year round"},
    "lettuce":            {"wiki": "Lettuce",              "yt": "growing lettuce seattle cool weather"},
    "sugar-snap-peas":    {"wiki": "Snap_pea",             "yt": "growing sugar snap peas pacific northwest"},
    "zucchini":           {"wiki": "Zucchini",             "yt": "how to grow zucchini squash seattle"},
    "garlic":             {"wiki": "Garlic",               "yt": "planting garlic fall pacific northwest"},
    "blueberries":        {"wiki": "Blueberry",            "yt": "growing blueberries pacific northwest acidic soil"},
    "strawberries":       {"wiki": "Strawberry",           "yt": "growing strawberries seattle hood variety"},
    "herbs-basil":        {"wiki": "Basil",                "yt": "growing basil seattle pacific northwest"},
    "herbs-rosemary":     {"wiki": "Rosemary",             "yt": "growing rosemary outdoors pacific northwest"},
    "beans-green":        {"wiki": "Green_bean",           "yt": "growing green beans pole bush pacific northwest"},
    "carrots":            {"wiki": "Carrot",               "yt": "growing carrots pacific northwest raised bed"},
    "potatoes":           {"wiki": "Potato",               "yt": "growing potatoes seattle raised bed container"},
    "beets":              {"wiki": "Beetroot",             "yt": "growing beets pacific northwest garden"},
    "cucumber":           {"wiki": "Cucumber",             "yt": "growing cucumbers seattle pacific northwest"},
    "chard":              {"wiki": "Chard",                "yt": "growing swiss chard pacific northwest"},
    "monstera-deliciosa": {"wiki": "Monstera_deliciosa",   "yt": "monstera deliciosa care indoor plant"},
    "pothos-golden":      {"wiki": "Epipremnum_aureum",    "yt": "golden pothos care tips low light"},
    "snake-plant":        {"wiki": "Dracaena_trifasciata", "yt": "snake plant care beginner houseplant"},
    "fiddle-leaf-fig":    {"wiki": "Ficus_lyrata",         "yt": "fiddle leaf fig care tips indoor"},
    "ferns":              {"wiki": "Nephrolepis_exaltata", "yt": "boston fern care indoor humidity"},
    "peace-lily":         {"wiki": "Spathiphyllum",        "yt": "peace lily care low light indoor plant"},
    "pilea":              {"wiki": "Pilea_peperomioides",   "yt": "pilea peperomioides care propagation"},
    "calathea":           {"wiki": "Goeppertia",           "yt": "calathea prayer plant care humidity"},
}


def _enrich(plant: dict) -> dict:
    """Add media URLs to a plant dict."""
    pid = plant["id"]
    media = _MEDIA.get(pid, {})
    plant["wiki"] = media.get("wiki", plant["name"].replace(" ", "_"))
    plant["youtube_search"] = media.get("yt", f"how to grow {plant['name']} pacific northwest")
    return plant


# Enrich all plants at import time
for _p in ALL_PLANTS:
    _enrich(_p)


def search_all(query: str = "", category: str = "", difficulty: str = "") -> list[dict]:
    """Search across all plants."""
    results = ALL_PLANTS
    if query:
        q = query.lower()
        results = [
            p for p in results
            if q in p["name"].lower()
            or q in p.get("id", "")
            or any(q in v.lower() for v in p.get("varieties", []))
            or q in p.get("pnw_notes", "").lower()
        ]
    if category:
        results = [p for p in results if p.get("category") == category]
    if difficulty:
        results = [p for p in results if p.get("difficulty") == difficulty]
    return results


def get_plant(plant_id: str) -> dict | None:
    """Get a plant by ID."""
    for p in ALL_PLANTS:
        if p["id"] == plant_id:
            return p
    return None
