"""
yplanter.plants_db
~~~~~~~~~~~~~~~~~~
Curated database of plants, vegetables, and yard suggestions
for Seattle / Pacific Northwest (USDA Zone 8b).
"""
from __future__ import annotations

# ─── Seattle / PNW Vegetables & Herbs ────────────────────────────────────────

VEGETABLES: list[dict] = [
    {
        "id": "tomato",
        "name": "Tomatoes",
        "emoji": "\U0001f345",
        "category": "vegetable",
        "varieties": ["Early Girl", "Sungold Cherry", "Stupice", "Black Krim", "Oregon Spring"],
        "pnw_notes": "Short-season varieties do best in Seattle. Start indoors Feb\u2013Mar, transplant after last frost (mid-Apr). Use black plastic mulch to warm soil.",
        "sun": "Full sun (8+ hrs)",
        "water": "1\u20132 inches/week, consistent",
        "soil": "Rich, well-drained, pH 6.0\u20136.8",
        "start_indoors": "Feb\u2013Mar",
        "transplant": "Mid Apr\u2013May",
        "direct_sow": None,
        "harvest": "Jul\u2013Oct",
        "spacing_in": 24,
        "difficulty": "moderate",
        "frost_hardy": False,
        "tip": "Sungold cherry tomatoes are bulletproof in Seattle. Pinch suckers for larger fruit on indeterminate types.",
        "companions": ["Basil", "Carrots", "Marigolds"],
        "avoid_near": ["Brassicas", "Fennel"],
    },
    {
        "id": "kale",
        "name": "Kale",
        "emoji": "\U0001f96c",
        "category": "vegetable",
        "varieties": ["Lacinato (Dinosaur)", "Red Russian", "Winterbor", "Dwarf Blue Curled"],
        "pnw_notes": "A PNW superstar. Can grow nearly year-round in Seattle. Sweeter after frost. Start in spring or late summer for fall/winter harvest.",
        "sun": "Full sun to part shade",
        "water": "1 inch/week",
        "soil": "Rich, well-drained, pH 6.0\u20137.0",
        "start_indoors": "Feb\u2013Mar (spring crop)",
        "transplant": "Mar\u2013Apr or Jul\u2013Aug",
        "direct_sow": "Mar\u2013Aug",
        "harvest": "Year-round (with protection)",
        "spacing_in": 18,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Lacinato kale is the Seattle gardener's best friend\u2014harvest outer leaves and it keeps producing for months.",
        "companions": ["Beets", "Celery", "Onions", "Potatoes"],
        "avoid_near": ["Strawberries"],
    },
    {
        "id": "lettuce",
        "name": "Lettuce & Salad Greens",
        "emoji": "\U0001f96c",
        "category": "vegetable",
        "varieties": ["Buttercrunch", "Red Sails", "Mesclun Mix", "Little Gem", "Winter Density"],
        "pnw_notes": "Thrives in Seattle's cool, mild climate. Direct sow early spring through fall. Bolts in summer heat\u2014plant in shade then.",
        "sun": "Part shade to full sun",
        "water": "Consistent moisture",
        "soil": "Loose, well-drained, pH 6.0\u20137.0",
        "start_indoors": None,
        "transplant": None,
        "direct_sow": "Mar\u2013Sep (succession plant every 2\u20133 weeks)",
        "harvest": "Apr\u2013Nov",
        "spacing_in": 8,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Succession sow every 2\u20133 weeks for continuous harvest. In summer, plant on the north side of taller crops for shade.",
        "companions": ["Carrots", "Radishes", "Strawberries"],
        "avoid_near": [],
    },
    {
        "id": "sugar-snap-peas",
        "name": "Sugar Snap Peas",
        "emoji": "\U0001f95c",
        "category": "vegetable",
        "varieties": ["Sugar Snap", "Cascadia", "Super Sugar Snap"],
        "pnw_notes": "A PNW spring classic. One of the earliest crops you can direct sow. Peas fix nitrogen in the soil for future crops.",
        "sun": "Full sun to part shade",
        "water": "Moderate, even moisture",
        "soil": "Well-drained, pH 6.0\u20137.5",
        "start_indoors": None,
        "transplant": None,
        "direct_sow": "Feb\u2013Mar (as soon as soil is workable)",
        "harvest": "May\u2013Jul",
        "spacing_in": 3,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Inoculate seeds with rhizobium bacteria for better nitrogen fixation. Provide a trellis for climbing types.",
        "companions": ["Carrots", "Radishes", "Spinach", "Corn"],
        "avoid_near": ["Onions", "Garlic"],
    },
    {
        "id": "zucchini",
        "name": "Zucchini & Summer Squash",
        "emoji": "\U0001f952",
        "category": "vegetable",
        "varieties": ["Black Beauty", "Costata Romanesco", "Gold Rush Yellow", "Pattypan"],
        "pnw_notes": "Very productive in Seattle summers. One or two plants can feed a family. Start indoors or direct sow after frost danger.",
        "sun": "Full sun (6+ hrs)",
        "water": "1\u20132 inches/week at base",
        "soil": "Rich, well-drained, pH 6.0\u20137.5",
        "start_indoors": "Apr",
        "transplant": "May",
        "direct_sow": "May\u2013Jun",
        "harvest": "Jul\u2013Oct",
        "spacing_in": 36,
        "difficulty": "easy",
        "frost_hardy": False,
        "tip": "Harvest when 6\u20138 inches for best flavor. Check daily\u2014they grow FAST. Hand-pollinate if bees are scarce early season.",
        "companions": ["Corn", "Beans", "Nasturtiums"],
        "avoid_near": ["Potatoes"],
    },
    {
        "id": "garlic",
        "name": "Garlic",
        "emoji": "\U0001f9c4",
        "category": "vegetable",
        "varieties": ["Music (hardneck)", "Chesnok Red", "Inchelium Red (softneck)", "Georgian Crystal"],
        "pnw_notes": "Plant in October for harvest next July. PNW is one of the best garlic-growing regions in the US. Hardneck types produce delicious scapes in spring.",
        "sun": "Full sun",
        "water": "Moderate\u2014reduce before harvest",
        "soil": "Loose, well-drained, pH 6.0\u20137.0",
        "start_indoors": None,
        "transplant": None,
        "direct_sow": "Oct\u2013Nov (fall planting)",
        "harvest": "Jul (following year)",
        "spacing_in": 6,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Snap off scapes in spring to redirect energy to bulbs. Cure for 2\u20134 weeks in a dry, shaded area before storing.",
        "companions": ["Tomatoes", "Roses", "Fruit trees"],
        "avoid_near": ["Beans", "Peas"],
    },
    {
        "id": "blueberries",
        "name": "Blueberries",
        "emoji": "\U0001fad0",
        "category": "fruit",
        "varieties": ["Duke (early)", "Bluecrop (mid)", "Elliott (late)", "Sunshine Blue (compact)"],
        "pnw_notes": "The PNW is blueberry country\u2014Washington is the #1 US producer. Acidic native soil is naturally perfect. Plant 2+ varieties for cross-pollination.",
        "sun": "Full sun",
        "water": "1\u20132 inches/week, consistent",
        "soil": "Acidic (pH 4.5\u20135.5), amended with peat/sulfur",
        "start_indoors": None,
        "transplant": "Early spring (bare root) or anytime (potted)",
        "direct_sow": None,
        "harvest": "Jun\u2013Sep",
        "spacing_in": 60,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Net bushes when berries ripen\u2014birds love them too. Mulch heavily with acidic material (pine bark, coffee grounds).",
        "companions": ["Rhododendrons", "Azaleas", "Strawberries"],
        "avoid_near": [],
    },
    {
        "id": "strawberries",
        "name": "Strawberries",
        "emoji": "\U0001f353",
        "category": "fruit",
        "varieties": ["Hood", "Totem", "Rainier", "Seascape (everbearing)", "Alpine"],
        "pnw_notes": "Hood strawberries are legendary in the PNW for their intense flavor. Plant in spring. Everbearing types fruit spring through fall.",
        "sun": "Full sun (6+ hrs)",
        "water": "1 inch/week, consistent",
        "soil": "Rich, well-drained, slightly acidic pH 5.5\u20136.5",
        "start_indoors": None,
        "transplant": "Mar\u2013Apr",
        "direct_sow": None,
        "harvest": "Jun (June-bearing) or Jun\u2013Oct (everbearing)",
        "spacing_in": 18,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Mulch with straw to keep berries clean. Pinch first-year flowers on June-bearers for a bigger second-year crop.",
        "companions": ["Borage", "Lettuce", "Spinach", "Beans"],
        "avoid_near": ["Brassicas", "Fennel"],
    },
    {
        "id": "herbs-basil",
        "name": "Basil",
        "emoji": "\U0001f33f",
        "category": "herb",
        "varieties": ["Genovese", "Thai", "Purple", "Lemon", "African Blue"],
        "pnw_notes": "Needs warmth\u2014start indoors and transplant after last frost. Grow against south-facing wall or use black mulch for extra warmth.",
        "sun": "Full sun (6+ hrs)",
        "water": "Moderate, consistent",
        "soil": "Rich, well-drained, pH 6.0\u20137.0",
        "start_indoors": "Mar\u2013Apr",
        "transplant": "May\u2013Jun",
        "direct_sow": None,
        "harvest": "Jun\u2013Oct",
        "spacing_in": 12,
        "difficulty": "moderate",
        "frost_hardy": False,
        "tip": "Pinch flower buds to extend harvest. Make pesto batches and freeze in ice cube trays for winter.",
        "companions": ["Tomatoes", "Peppers"],
        "avoid_near": ["Sage", "Rue"],
    },
    {
        "id": "herbs-rosemary",
        "name": "Rosemary",
        "emoji": "\U0001f33f",
        "category": "herb",
        "varieties": ["Arp (hardiest)", "Tuscan Blue", "Prostrate/Trailing", "Miss Jessup"],
        "pnw_notes": "Perennial in Seattle\u2014once established, it thrives with minimal care. Arp variety is the hardiest for PNW winters.",
        "sun": "Full sun",
        "water": "Low\u2014drought tolerant once established",
        "soil": "Sandy, well-drained, pH 6.0\u20137.0",
        "start_indoors": None,
        "transplant": "Spring",
        "direct_sow": None,
        "harvest": "Year-round",
        "spacing_in": 24,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Plant by a sunny wall for extra warmth and drainage. Excellent in containers on patios.",
        "companions": ["Sage", "Thyme", "Lavender"],
        "avoid_near": [],
    },
    {
        "id": "beans-green",
        "name": "Green Beans",
        "emoji": "\U0001f33f",
        "category": "vegetable",
        "varieties": ["Provider (bush)", "Blue Lake (bush/pole)", "Kentucky Wonder (pole)", "Scarlet Runner"],
        "pnw_notes": "Direct sow after soil warms to 60\u00b0F. Bush types are quicker to harvest; pole types produce longer.",
        "sun": "Full sun (6+ hrs)",
        "water": "1 inch/week",
        "soil": "Well-drained, pH 6.0\u20137.0",
        "start_indoors": None,
        "transplant": None,
        "direct_sow": "May\u2013Jun (after soil warms to 60\u00b0F)",
        "harvest": "Jul\u2013Oct",
        "spacing_in": 4,
        "difficulty": "easy",
        "frost_hardy": False,
        "tip": "Pick frequently to keep plants producing. Scarlet Runner beans have gorgeous flowers that attract hummingbirds.",
        "companions": ["Corn", "Squash", "Cucumbers"],
        "avoid_near": ["Onions", "Garlic"],
    },
    {
        "id": "carrots",
        "name": "Carrots",
        "emoji": "\U0001f955",
        "category": "vegetable",
        "varieties": ["Nantes (Bolero)", "Danvers", "Scarlet Nantes", "Purple Haze", "Little Finger"],
        "pnw_notes": "Thrive in PNW's cool weather. Direct sow spring through mid-summer. Can overwinter in the ground with mulch for winter harvest.",
        "sun": "Full sun to part shade",
        "water": "Consistent moisture for even growth",
        "soil": "Loose, sandy, rock-free, pH 6.0\u20136.8",
        "start_indoors": None,
        "transplant": None,
        "direct_sow": "Mar\u2013Jul",
        "harvest": "Jun\u2013Dec (can overwinter)",
        "spacing_in": 3,
        "difficulty": "moderate",
        "frost_hardy": True,
        "tip": "Sow seeds on the surface and barely cover. Mix with radish seeds as row markers. Thin ruthlessly for straight roots.",
        "companions": ["Peas", "Lettuce", "Tomatoes", "Onions"],
        "avoid_near": ["Dill"],
    },
    {
        "id": "potatoes",
        "name": "Potatoes",
        "emoji": "\U0001f954",
        "category": "vegetable",
        "varieties": ["Yukon Gold", "Red Pontiac", "Fingerling", "Purple Majesty", "All Blue"],
        "pnw_notes": "Plant seed potatoes in March\u2013April. Hill soil around stems as they grow. Easy and rewarding\u2014great for kids!",
        "sun": "Full sun (6+ hrs)",
        "water": "Consistent, 1\u20132 inches/week",
        "soil": "Loose, well-drained, slightly acidic pH 5.0\u20136.0",
        "start_indoors": None,
        "transplant": None,
        "direct_sow": "Mar\u2013Apr",
        "harvest": "Jul\u2013Sep",
        "spacing_in": 12,
        "difficulty": "easy",
        "frost_hardy": False,
        "tip": "Grow in raised beds or bags for easy harvest. Don't wash before storing\u2014brush off soil and cure in dark for 2 weeks.",
        "companions": ["Beans", "Corn", "Horseradish"],
        "avoid_near": ["Tomatoes", "Squash"],
    },
    {
        "id": "beets",
        "name": "Beets",
        "emoji": "\U0001f534",
        "category": "vegetable",
        "varieties": ["Detroit Dark Red", "Chioggia (candy stripe)", "Golden", "Bull's Blood"],
        "pnw_notes": "Cool-weather crop perfect for PNW. Direct sow spring and late summer for fall harvest. Greens are edible and nutritious too!",
        "sun": "Full sun to part shade",
        "water": "Consistent moisture",
        "soil": "Loose, well-drained, pH 6.0\u20137.0",
        "start_indoors": None,
        "transplant": None,
        "direct_sow": "Mar\u2013Jul",
        "harvest": "May\u2013Nov",
        "spacing_in": 4,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Each beet 'seed' is actually a cluster\u2014thin to one seedling per cluster. Roast Chioggia beets for stunning candy-striped rounds.",
        "companions": ["Onions", "Lettuce", "Cabbage"],
        "avoid_near": ["Pole beans"],
    },
    {
        "id": "cucumber",
        "name": "Cucumbers",
        "emoji": "\U0001f952",
        "category": "vegetable",
        "varieties": ["Marketmore 76", "Lemon Cucumber", "Diva", "Suyo Long", "Tasty Jade"],
        "pnw_notes": "Need warm soil\u2014start indoors or wait until late May to direct sow. Use a trellis for straighter fruit and better air circulation.",
        "sun": "Full sun (6+ hrs)",
        "water": "1\u20132 inches/week, consistent",
        "soil": "Rich, well-drained, pH 6.0\u20137.0",
        "start_indoors": "Apr",
        "transplant": "Late May\u2013Jun",
        "direct_sow": "Late May\u2013Jun",
        "harvest": "Jul\u2013Sep",
        "spacing_in": 18,
        "difficulty": "moderate",
        "frost_hardy": False,
        "tip": "Pick cucumbers when young for crispest texture. Lemon cucumbers are a fun PNW heirloom\u2014round, yellow, and mild.",
        "companions": ["Beans", "Peas", "Sunflowers"],
        "avoid_near": ["Potatoes", "Aromatic herbs"],
    },
    {
        "id": "chard",
        "name": "Swiss Chard",
        "emoji": "\U0001f308",
        "category": "vegetable",
        "varieties": ["Bright Lights", "Fordhook Giant", "Ruby Red", "Peppermint"],
        "pnw_notes": "Almost as hardy as kale in Seattle. Beautiful ornamental AND edible. Tolerates light frost and partial shade.",
        "sun": "Full sun to part shade",
        "water": "1 inch/week",
        "soil": "Rich, well-drained, pH 6.0\u20137.0",
        "start_indoors": None,
        "transplant": None,
        "direct_sow": "Apr\u2013Aug",
        "harvest": "Jun\u2013Nov",
        "spacing_in": 12,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Bright Lights variety has stunning rainbow stems\u2014doubles as edible landscaping. Harvest outer leaves for continuous production.",
        "companions": ["Beans", "Cabbage", "Onions"],
        "avoid_near": [],
    },
    {
        "id": "broccoli",
        "name": "Broccoli",
        "emoji": "\U0001f966",
        "category": "vegetable",
        "varieties": ["Waltham 29", "De Cicco", "Belstar", "Purple Sprouting"],
        "pnw_notes": "Cool-weather champion in Seattle. Plant in early spring or late summer for fall harvest. Purple sprouting types overwinter beautifully.",
        "sun": "Full sun (6+ hrs)",
        "water": "1\u20131.5 inches/week, consistent",
        "soil": "Rich, well-drained, pH 6.0\u20137.0",
        "start_indoors": "Feb\u2013Mar (spring) or Jun\u2013Jul (fall)",
        "transplant": "Mar\u2013Apr or Jul\u2013Aug",
        "direct_sow": None,
        "harvest": "May\u2013Jun (spring) or Oct\u2013Dec (fall)",
        "spacing_in": 18,
        "difficulty": "moderate",
        "frost_hardy": True,
        "tip": "Purple Sprouting broccoli is a PNW secret\u2014plant in summer, harvest shoots all winter long.",
        "companions": ["Onions", "Celery", "Potatoes", "Dill"],
        "avoid_near": ["Tomatoes", "Strawberries"],
    },
    {
        "id": "spinach",
        "name": "Spinach",
        "emoji": "\U0001f96c",
        "category": "vegetable",
        "varieties": ["Bloomsdale Long Standing", "Space", "Tyee", "Giant Winter"],
        "pnw_notes": "Thrives in Seattle\u2019s cool, overcast springs and falls. Bolts quickly in summer heat\u2014grow as a cool-season crop. Can overwinter with protection.",
        "sun": "Part shade to full sun",
        "water": "Consistent moisture",
        "soil": "Rich, well-drained, pH 6.5\u20137.5",
        "start_indoors": None,
        "transplant": None,
        "direct_sow": "Feb\u2013Apr, Aug\u2013Sep",
        "harvest": "Apr\u2013Jun, Sep\u2013Nov",
        "spacing_in": 6,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Giant Winter variety is bred for PNW fall/winter growing. Sow thickly and harvest as baby greens for fastest results.",
        "companions": ["Strawberries", "Peas", "Beans"],
        "avoid_near": [],
    },
    {
        "id": "peppers",
        "name": "Peppers",
        "emoji": "\U0001f336\ufe0f",
        "category": "vegetable",
        "varieties": ["Jimmy Nardello", "Shishito", "Early Jalape\u00f1o", "Carmen", "Gypsy"],
        "pnw_notes": "Challenging in Seattle\u2014need warmth. Start early indoors, transplant to warmest spot after last frost. Black plastic mulch and wall-o-water help enormously.",
        "sun": "Full sun (8+ hrs)",
        "water": "1 inch/week, consistent",
        "soil": "Rich, well-drained, pH 6.0\u20136.8",
        "start_indoors": "Feb\u2013Mar",
        "transplant": "Late May\u2013Jun",
        "direct_sow": None,
        "harvest": "Aug\u2013Oct",
        "spacing_in": 18,
        "difficulty": "hard",
        "frost_hardy": False,
        "tip": "Shishito and Jimmy Nardello are the most reliable peppers for Seattle\u2014they ripen even in cooler summers.",
        "companions": ["Basil", "Tomatoes", "Carrots"],
        "avoid_near": ["Fennel", "Brassicas"],
    },
    {
        "id": "radishes",
        "name": "Radishes",
        "emoji": "\U0001f534",
        "category": "vegetable",
        "varieties": ["Cherry Belle", "French Breakfast", "Watermelon Radish", "Daikon"],
        "pnw_notes": "One of the fastest crops\u2014ready in 25\u201330 days. Perfect for filling gaps between longer crops. Succession sow spring through fall.",
        "sun": "Full sun to part shade",
        "water": "Even moisture for mild flavor",
        "soil": "Loose, well-drained, pH 6.0\u20137.0",
        "start_indoors": None,
        "transplant": None,
        "direct_sow": "Mar\u2013Sep (succession sow every 2 weeks)",
        "harvest": "Apr\u2013Oct (25\u201360 days depending on variety)",
        "spacing_in": 2,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Watermelon radish is stunning sliced thin\u2014white outside, bright pink inside. Takes 50\u201360 days vs 25 for regular radishes.",
        "companions": ["Lettuce", "Peas", "Spinach", "Carrots"],
        "avoid_near": [],
    },
    {
        "id": "brussels-sprouts",
        "name": "Brussels Sprouts",
        "emoji": "\U0001f7e2",
        "category": "vegetable",
        "varieties": ["Long Island Improved", "Diablo", "Jade Cross", "Falstaff (purple)"],
        "pnw_notes": "A PNW fall/winter star. Flavor improves dramatically after frost. Start in spring for fall/winter harvest. Can harvest into January.",
        "sun": "Full sun (6+ hrs)",
        "water": "1\u20131.5 inches/week",
        "soil": "Rich, firm, well-drained, pH 6.0\u20137.5",
        "start_indoors": "Apr\u2013May",
        "transplant": "Jun\u2013Jul",
        "direct_sow": None,
        "harvest": "Oct\u2013Jan",
        "spacing_in": 24,
        "difficulty": "moderate",
        "frost_hardy": True,
        "tip": "Remove lower leaves as sprouts develop to improve air circulation. Harvest from bottom up\u2014lower sprouts mature first.",
        "companions": ["Onions", "Beets", "Carrots", "Dill"],
        "avoid_near": ["Strawberries", "Tomatoes"],
    },
    {
        "id": "winter-squash",
        "name": "Winter Squash",
        "emoji": "\U0001f383",
        "category": "vegetable",
        "varieties": ["Delicata", "Butternut (Waltham)", "Acorn", "Sugar Pie Pumpkin", "Red Kuri"],
        "pnw_notes": "Needs warm summer months but stores for months after harvest. Delicata is the most reliable in Seattle\u2019s shorter season. Cure before storing.",
        "sun": "Full sun (6+ hrs)",
        "water": "1\u20132 inches/week at base",
        "soil": "Rich, well-drained, pH 6.0\u20137.0",
        "start_indoors": "Apr",
        "transplant": "Late May\u2013Jun",
        "direct_sow": "Late May\u2013Jun",
        "harvest": "Sep\u2013Oct",
        "spacing_in": 48,
        "difficulty": "moderate",
        "frost_hardy": False,
        "tip": "Cure squash in the sun for 10\u201314 days after harvest, then store in a cool (50\u00b0F) dry place. Properly cured squash lasts 3\u20136 months.",
        "companions": ["Corn", "Beans", "Nasturtiums"],
        "avoid_near": ["Potatoes"],
    },
    {
        "id": "raspberries",
        "name": "Raspberries",
        "emoji": "\U0001f347",
        "category": "fruit",
        "varieties": ["Meeker", "Tulameen", "Heritage (everbearing)", "Fall Gold (yellow)", "Cascade Delight"],
        "pnw_notes": "The PNW produces 90% of US raspberries\u2014our climate is perfect. Plant bare-root canes in early spring. Extremely productive once established.",
        "sun": "Full sun (6+ hrs)",
        "water": "1\u20132 inches/week during fruiting",
        "soil": "Well-drained, slightly acidic pH 5.5\u20136.5",
        "start_indoors": None,
        "transplant": "Feb\u2013Mar (bare root)",
        "direct_sow": None,
        "harvest": "Jun\u2013Jul (summer) or Aug\u2013Oct (everbearing)",
        "spacing_in": 24,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Prune summer-bearing types after harvest (remove fruited canes). For everbearing, mow all canes in winter for one big fall crop.",
        "companions": ["Garlic", "Tansy", "Turnips"],
        "avoid_near": ["Blackberries", "Potatoes"],
    },
    {
        "id": "apples",
        "name": "Apple Trees",
        "emoji": "\U0001f34e",
        "category": "fruit",
        "varieties": ["Honeycrisp", "Liberty", "Gravenstein", "King", "Jonagold"],
        "pnw_notes": "Washington is the #1 apple-producing state. Most varieties thrive here. Plant two compatible varieties for cross-pollination. Dwarf rootstocks work great in small yards.",
        "sun": "Full sun (6+ hrs)",
        "water": "1\u20132 inches/week for young trees",
        "soil": "Well-drained, pH 6.0\u20137.0",
        "start_indoors": None,
        "transplant": "Dec\u2013Mar (bare root) or anytime (potted)",
        "direct_sow": None,
        "harvest": "Aug\u2013Oct (depending on variety)",
        "spacing_in": 120,
        "difficulty": "moderate",
        "frost_hardy": True,
        "tip": "Liberty is disease-resistant and low-maintenance\u2014perfect for organic home orchards. Thin fruit in June to 1 apple per cluster for bigger fruit.",
        "companions": ["Chives", "Comfrey", "Nasturtiums"],
        "avoid_near": ["Walnuts"],
        "fertilizer": "Balanced organic fertilizer in early spring. Avoid high nitrogen after June.",
    },
    {
        "id": "figs",
        "name": "Fig Trees",
        "emoji": "\U0001f351",
        "category": "fruit",
        "varieties": ["Desert King", "Lattarula (Italian Honey)", "Olympian", "Chicago Hardy"],
        "pnw_notes": "Yes, figs grow in Seattle! Desert King is the classic PNW variety\u2014needs no pollination and ripens reliably. Plant against a south-facing wall for extra warmth.",
        "sun": "Full sun, south-facing wall ideal",
        "water": "Moderate once established",
        "soil": "Well-drained, pH 6.0\u20136.5",
        "start_indoors": None,
        "transplant": "Spring",
        "direct_sow": None,
        "harvest": "Aug\u2013Sep",
        "spacing_in": 120,
        "difficulty": "moderate",
        "frost_hardy": False,
        "tip": "Desert King produces one crop on last year\u2019s wood. Don\u2019t prune heavily or you\u2019ll lose the crop. Wrap young trees in burlap during hard freezes.",
        "companions": ["Rue", "Comfrey"],
        "avoid_near": [],
    },
    {
        "id": "herbs-cilantro",
        "name": "Cilantro / Coriander",
        "emoji": "\U0001f33f",
        "category": "herb",
        "varieties": ["Santo (slow-bolt)", "Calypso", "Long Standing"],
        "pnw_notes": "Bolts quickly in heat. Best grown in spring and fall in Seattle. Let some plants go to seed for coriander spice and self-sowing next year.",
        "sun": "Part shade to full sun",
        "water": "Consistent moisture",
        "soil": "Well-drained, pH 6.2\u20136.8",
        "start_indoors": None,
        "transplant": None,
        "direct_sow": "Mar\u2013May, Aug\u2013Sep (succession sow every 3 weeks)",
        "harvest": "Apr\u2013Jun, Sep\u2013Nov (leaves); Jul\u2013Aug (coriander seed)",
        "spacing_in": 6,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Santo variety is the slowest to bolt. Once it flowers, let seeds dry on the plant\u2014that\u2019s coriander! Crush for cooking or save for next year.",
        "companions": ["Tomatoes", "Lettuce", "Beans"],
        "avoid_near": ["Fennel"],
    },
    {
        "id": "herbs-thyme",
        "name": "Thyme",
        "emoji": "\U0001f33f",
        "category": "herb",
        "varieties": ["English (common)", "French", "Lemon", "Creeping"],
        "pnw_notes": "Perennial in Seattle\u2014thrives in poor, well-drained soil. Creeping thyme makes a beautiful drought-tolerant groundcover or lawn alternative.",
        "sun": "Full sun",
        "water": "Low\u2014drought tolerant once established",
        "soil": "Sandy, well-drained, pH 6.0\u20138.0",
        "start_indoors": None,
        "transplant": "Spring",
        "direct_sow": None,
        "harvest": "Year-round",
        "spacing_in": 12,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Plant creeping thyme between pavers or as a lawn substitute\u2014it releases fragrance when stepped on and needs almost no water.",
        "companions": ["Rosemary", "Lavender", "Sage", "Strawberries"],
        "avoid_near": [],
    },
    {
        "id": "herbs-mint",
        "name": "Mint",
        "emoji": "\U0001f33f",
        "category": "herb",
        "varieties": ["Spearmint", "Peppermint", "Chocolate Mint", "Mojito Mint"],
        "pnw_notes": "Grows aggressively in PNW climate\u2014always plant in containers or it will take over your garden. Thrives in Seattle\u2019s moist conditions.",
        "sun": "Part shade to full sun",
        "water": "Keep moist",
        "soil": "Rich, moist, pH 6.0\u20137.0",
        "start_indoors": None,
        "transplant": "Spring",
        "direct_sow": None,
        "harvest": "Year-round (evergreen in mild PNW winters)",
        "spacing_in": 18,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Grow in a large pot sunk into the ground to contain spreading. Harvest frequently for bushier growth. Makes excellent tea fresh or dried.",
        "companions": ["Cabbage", "Tomatoes"],
        "avoid_near": ["Parsley"],
    },
    {
        "id": "rhododendron",
        "name": "Rhododendron",
        "emoji": "\U0001f338",
        "category": "shrub",
        "varieties": ["PJM (compact, cold-hardy)", "Roseum Elegans", "Yakushimanum hybrids", "Nova Zembla"],
        "pnw_notes": "Washington\u2019s state flower\u2014grows naturally in PNW forests. Prefers acidic soil (common in Seattle). Provides year-round evergreen structure with spectacular spring blooms.",
        "sun": "Part shade to filtered sun",
        "water": "Regular, consistent moisture",
        "soil": "Acidic (pH 4.5\u20135.5), well-drained, rich in organic matter",
        "start_indoors": None,
        "transplant": "Fall or spring",
        "direct_sow": None,
        "harvest": None,
        "bloom": "Apr\u2013Jun",
        "spacing_in": 60,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Never plant too deep\u2014rhododendrons have shallow root systems. Mulch with acidic material (pine bark) but keep mulch away from trunk.",
        "companions": ["Azaleas", "Ferns", "Hostas", "Blueberries"],
        "avoid_near": [],
    },
    {
        "id": "hydrangea",
        "name": "Hydrangea",
        "emoji": "\U0001f490",
        "category": "shrub",
        "varieties": ["Endless Summer (mophead)", "Limelight (panicle)", "Annabelle (smooth)", "Nikko Blue"],
        "pnw_notes": "Thrives in Seattle\u2019s climate. Flower color (pink vs blue) depends on soil pH\u2014Seattle\u2019s acidic soil naturally produces blue blooms. Panicle types are most reliable.",
        "sun": "Morning sun, afternoon shade",
        "water": "Regular\u2014name means \u2018water vessel\u2019 in Greek",
        "soil": "Rich, moist, well-drained; acidic for blue, alkaline for pink",
        "start_indoors": None,
        "transplant": "Fall or spring",
        "direct_sow": None,
        "harvest": None,
        "bloom": "Jun\u2013Oct",
        "spacing_in": 48,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "To keep flowers blue in Seattle, add aluminum sulfate. For pink, add garden lime. Dried flower heads look beautiful left on through winter.",
        "companions": ["Hostas", "Ferns", "Astilbe"],
        "avoid_near": [],
    },
    {
        "id": "lilac",
        "name": "Lilac",
        "emoji": "\U0001f4ae",
        "category": "shrub",
        "varieties": ["Common (Syringa vulgaris)", "Sensation (bicolor)", "Miss Kim (compact)", "Bloomerang (reblooming)"],
        "pnw_notes": "Classic spring fragrance. Needs some winter chill to bloom well\u2014Seattle provides just enough. Plant in full sun for best flowering. Bloomerang varieties rebloom in fall.",
        "sun": "Full sun (6+ hrs)",
        "water": "Moderate once established",
        "soil": "Well-drained, neutral to slightly alkaline pH 6.5\u20137.5",
        "start_indoors": None,
        "transplant": "Fall or spring",
        "direct_sow": None,
        "harvest": None,
        "bloom": "Apr\u2013May (spring); Sep\u2013Oct (reblooming types)",
        "spacing_in": 72,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Prune immediately after spring bloom\u2014lilacs set next year\u2019s buds in summer. Remove spent flowers and suckers to maintain shape.",
        "companions": ["Peonies", "Iris", "Daylilies"],
        "avoid_near": [],
    },
    {
        "id": "camellia",
        "name": "Camellia",
        "emoji": "\U0001f33a",
        "category": "shrub",
        "varieties": ["Japonica (spring bloom)", "Sasanqua (fall bloom)", "Yuletide (red, winter)", "Debutante (pink)"],
        "pnw_notes": "One of few shrubs that blooms in Seattle\u2019s dark winter months. Evergreen, elegant, and well-suited to PNW\u2019s acidic soil and mild winters.",
        "sun": "Part shade\u2014protect from morning sun on frozen buds",
        "water": "Regular, consistent moisture",
        "soil": "Acidic (pH 5.0\u20136.5), well-drained, rich",
        "start_indoors": None,
        "transplant": "Fall or spring",
        "direct_sow": None,
        "harvest": None,
        "bloom": "Oct\u2013Apr (varies by variety)",
        "spacing_in": 72,
        "difficulty": "moderate",
        "frost_hardy": True,
        "tip": "Sasanqua camellias are more sun-tolerant and earlier-blooming than Japonicas. Yuletide variety gives red flowers at Christmas.",
        "companions": ["Rhododendrons", "Azaleas", "Ferns", "Hostas"],
        "avoid_near": [],
    },
    {
        "id": "japanese-maple",
        "name": "Japanese Maple",
        "emoji": "\U0001f341",
        "category": "tree",
        "varieties": ["Bloodgood (upright, dark red)", "Sango Kaku (coral bark)", "Crimson Queen (weeping)", "Osakazuki"],
        "pnw_notes": "Seattle\u2019s most popular ornamental tree. Hundreds of varieties thrive in our mild, humid climate. Stunning fall color. Protect from hot afternoon sun and drying east winds.",
        "sun": "Part shade to filtered sun",
        "water": "Regular, consistent\u2014don\u2019t let dry out",
        "soil": "Well-drained, slightly acidic pH 5.5\u20136.5, rich in organic matter",
        "start_indoors": None,
        "transplant": "Fall or early spring",
        "direct_sow": None,
        "harvest": None,
        "bloom": "Apr\u2013May (flowers); Oct\u2013Nov (peak fall color)",
        "spacing_in": 120,
        "difficulty": "moderate",
        "frost_hardy": True,
        "tip": "Avoid heavy pruning\u2014Japanese maples have a natural graceful shape. Water deeply during Seattle\u2019s dry summers. Mulch to protect shallow roots.",
        "companions": ["Hostas", "Ferns", "Azaleas", "Moss"],
        "avoid_near": [],
    },
    {
        "id": "dogwood",
        "name": "Pacific Dogwood",
        "emoji": "\U0001f333",
        "category": "tree",
        "varieties": ["Cornus nuttallii (native)", "Eddie\u2019s White Wonder (hybrid)", "Venus (large-bracted)"],
        "pnw_notes": "Washington\u2019s state tree. Elegant white bracts in spring, red berries in fall, and beautiful winter bark. Native to PNW forests\u2014naturally suited to our climate.",
        "sun": "Part shade to full sun",
        "water": "Moderate\u2014consistent moisture",
        "soil": "Well-drained, slightly acidic, rich in organic matter",
        "start_indoors": None,
        "transplant": "Fall or spring",
        "direct_sow": None,
        "harvest": None,
        "bloom": "Apr\u2013May (white bracts); Sep\u2013Oct (fall color)",
        "spacing_in": 180,
        "difficulty": "moderate",
        "frost_hardy": True,
        "tip": "Eddie\u2019s White Wonder hybrid is disease-resistant and easier than the pure native. Avoid disturbing roots\u2014dogwoods don\u2019t like being transplanted.",
        "companions": ["Rhododendrons", "Sword Ferns", "Salal"],
        "avoid_near": [],
    },
    {
        "id": "cherry-ornamental",
        "name": "Ornamental Cherry",
        "emoji": "\U0001f338",
        "category": "tree",
        "varieties": ["Yoshino (Somei-Yoshino)", "Akebono (pink cloud)", "Kwanzan (double pink)", "Okame (early, compact)"],
        "pnw_notes": "Seattle is famous for cherry blossoms\u2014the UW Quad\u2019s Yoshino cherries draw thousands each spring. Fast-growing, stunning display. Short-lived (30\u201350 years) but worth every year.",
        "sun": "Full sun (6+ hrs)",
        "water": "Regular when young, moderate once established",
        "soil": "Well-drained, pH 6.0\u20137.0",
        "start_indoors": None,
        "transplant": "Fall or spring (bare root) or anytime (potted)",
        "direct_sow": None,
        "harvest": None,
        "bloom": "Mar\u2013Apr (2\u20133 week peak bloom)",
        "spacing_in": 240,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Yoshino cherries bloom earliest (late March). Kwanzan blooms later with double flowers that last longer. Visit the UW campus or Seward Park for Seattle\u2019s best displays.",
        "companions": ["Daffodils", "Azaleas", "Ferns"],
        "avoid_near": [],
    },
    {
        "id": "lavender",
        "name": "Lavender",
        "emoji": "\U0001f49c",
        "category": "perennial",
        "varieties": ["English (Hidcote, Munstead)", "French (Grosso, Provence)", "Spanish (Stoechas)"],
        "pnw_notes": "Thrives in Seattle\u2019s dry summers. English varieties are hardiest for PNW winters. Excellent for borders, walkways, and pollinator gardens. Lavender farms dot the San Juan Islands and Sequim.",
        "sun": "Full sun (6+ hrs)",
        "water": "Low\u2014drought tolerant once established",
        "soil": "Sandy, well-drained, pH 6.5\u20137.5 (add lime to acidic PNW soil)",
        "start_indoors": None,
        "transplant": "Spring",
        "direct_sow": None,
        "harvest": None,
        "bloom": "Jun\u2013Aug",
        "spacing_in": 18,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Add gravel or pumice to planting hole for drainage\u2014lavender hates wet feet in PNW winters. Prune in spring, never into old wood.",
        "companions": ["Rosemary", "Thyme", "Roses", "Echinacea"],
        "avoid_near": [],
    },
    {
        "id": "dahlia",
        "name": "Dahlia",
        "emoji": "\U0001f33c",
        "category": "perennial",
        "varieties": ["Dinner Plate (huge blooms)", "Ball / Pompon", "Cactus", "Cafe au Lait (popular)"],
        "pnw_notes": "Seattle\u2019s unofficial flower! The American Dahlia Society was founded in WA. Plant tubers after last frost. Dig up tubers before hard frost for winter storage, or mulch heavily.",
        "sun": "Full sun (6+ hrs)",
        "water": "1\u20132 inches/week during growth",
        "soil": "Rich, well-drained, pH 6.5\u20137.0",
        "start_indoors": None,
        "transplant": "May (after last frost)",
        "direct_sow": None,
        "harvest": None,
        "bloom": "Jul\u2013Oct (until first frost)",
        "spacing_in": 24,
        "difficulty": "moderate",
        "frost_hardy": False,
        "tip": "Pinch the center growing tip when plants are 12\u2033 tall to encourage branching and more blooms. Stake tall dinner plate varieties early.",
        "companions": ["Marigolds", "Zinnias", "Salvia"],
        "avoid_near": [],
    },
    {
        "id": "peony",
        "name": "Peony",
        "emoji": "\U0001f33a",
        "category": "perennial",
        "varieties": ["Sarah Bernhardt (double pink)", "Karl Rosenfield (red)", "Bowl of Beauty (bicolor)", "Bartzella (Itoh, yellow)"],
        "pnw_notes": "Long-lived perennial that blooms spectacularly each spring. Seattle provides perfect winter chill for bud development. Once established, peonies can live 50+ years with minimal care.",
        "sun": "Full sun (6+ hrs)",
        "water": "Moderate\u2014regular during growth, less after bloom",
        "soil": "Rich, well-drained, pH 6.5\u20137.0",
        "start_indoors": None,
        "transplant": "Fall (Sep\u2013Oct is ideal)",
        "direct_sow": None,
        "harvest": None,
        "bloom": "May\u2013Jun",
        "spacing_in": 36,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Plant tubers with eyes (buds) exactly 1\u20132\u2033 below soil surface\u2014too deep and they won\u2019t bloom. Support heavy blooms with peony rings.",
        "companions": ["Roses", "Lavender", "Iris", "Alliums"],
        "avoid_near": [],
    },
    {
        "id": "hostas",
        "name": "Hostas",
        "emoji": "\U0001f33f",
        "category": "perennial",
        "varieties": ["Sum and Substance (giant, gold)", "Blue Angel", "Patriot (variegated)", "June (multi-color)"],
        "pnw_notes": "Seattle\u2019s shade gardens love hostas. Our mild, moist climate creates lush specimens. Main challenge is slugs\u2014organic iron phosphate bait is pet-safe and effective.",
        "sun": "Part shade to full shade",
        "water": "Regular, consistent moisture",
        "soil": "Rich, moist, well-drained, pH 6.0\u20137.0",
        "start_indoors": None,
        "transplant": "Spring or fall",
        "direct_sow": None,
        "harvest": None,
        "bloom": "Jul\u2013Aug (lavender flower spikes)",
        "spacing_in": 24,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Blue-leafed varieties need more shade; gold varieties tolerate more sun. Divide clumps every 3\u20134 years in spring to rejuvenate and share.",
        "companions": ["Ferns", "Astilbe", "Heuchera", "Japanese Maple"],
        "avoid_near": [],
    },
    {
        "id": "echinacea",
        "name": "Echinacea / Coneflower",
        "emoji": "\U0001f33b",
        "category": "perennial",
        "varieties": ["Magnus (classic purple)", "White Swan", "Cheyenne Spirit (color mix)", "PowWow Wild Berry"],
        "pnw_notes": "Native prairie plant that thrives in Seattle\u2019s sunny spots. Drought-tolerant once established. Attracts butterflies, bees, and seed-eating birds. Medicinal properties.",
        "sun": "Full sun (6+ hrs)",
        "water": "Low to moderate\u2014drought tolerant once established",
        "soil": "Well-drained, average\u2014thrives in lean soil",
        "start_indoors": "Mar (8\u201310 weeks before last frost)",
        "transplant": "May or fall",
        "direct_sow": "Apr\u2013May",
        "harvest": None,
        "bloom": "Jun\u2013Sep",
        "spacing_in": 18,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Leave spent flower heads through winter\u2014goldfinches love the seeds. Deadhead early blooms to encourage reblooming. Self-sows freely.",
        "companions": ["Lavender", "Black-eyed Susan", "Ornamental Grasses"],
        "avoid_near": [],
    },
    {
        "id": "heather",
        "name": "Heather / Heath",
        "emoji": "\U0001f3f5\ufe0f",
        "category": "perennial",
        "varieties": ["Calluna vulgaris (summer/fall)", "Erica carnea (winter bloom)", "Erica x darleyensis (winter/spring)"],
        "pnw_notes": "Evergreen groundcover that blooms when little else does\u2014winter-blooming varieties are especially valuable in Seattle. Thrives in our acidic soil and mild winters.",
        "sun": "Full sun to part shade",
        "water": "Low once established\u2014good drainage essential",
        "soil": "Acidic (pH 4.5\u20135.5), well-drained, lean",
        "start_indoors": None,
        "transplant": "Spring or fall",
        "direct_sow": None,
        "harvest": None,
        "bloom": "Nov\u2013Apr (winter types) or Jul\u2013Sep (summer types)",
        "spacing_in": 18,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Shear after blooming to keep compact. Mix winter-blooming Erica with summer-blooming Calluna for year-round color.",
        "companions": ["Rhododendrons", "Blueberries", "Conifers"],
        "avoid_near": [],
    },
    {
        "id": "sunflowers",
        "name": "Sunflowers",
        "emoji": "\U0001f33b",
        "category": "annual",
        "varieties": ["Mammoth (giant)", "Teddy Bear (dwarf, fluffy)", "Autumn Beauty (multi-color)", "Sunrich (pollenless, for cutting)"],
        "pnw_notes": "Easy, rewarding summer annual. Direct sow after last frost. Giant varieties can reach 10+ feet in Seattle\u2019s long summer days. Great for kids\u2019 gardens!",
        "sun": "Full sun (6+ hrs)",
        "water": "Regular until established, then moderate",
        "soil": "Average, well-drained, pH 6.0\u20137.5",
        "start_indoors": "Apr",
        "transplant": None,
        "direct_sow": "May\u2013Jun (after last frost)",
        "harvest": None,
        "bloom": "Jul\u2013Sep",
        "spacing_in": 18,
        "difficulty": "easy",
        "frost_hardy": False,
        "tip": "Leave spent heads for birds\u2014chickadees and goldfinches feast on the seeds. Succession plant every 2 weeks for continuous blooms.",
        "companions": ["Corn", "Squash", "Cucumbers"],
        "avoid_near": ["Potatoes"],
    },
    {
        "id": "sweet-peas",
        "name": "Sweet Peas",
        "emoji": "\U0001f380",
        "category": "annual",
        "varieties": ["Spencer (large, fragrant)", "Old Spice Mix", "Cupani (intensely scented)", "Royal Family (heat-tolerant)"],
        "pnw_notes": "Classic PNW cottage garden flower. Seattle\u2019s cool springs are ideal\u2014sweet peas fade in summer heat. Sow early for longest bloom season. Intoxicating fragrance.",
        "sun": "Full sun (6+ hrs)",
        "water": "Regular, consistent moisture",
        "soil": "Rich, well-drained, pH 7.0\u20137.5",
        "start_indoors": "Feb (soak seeds overnight)",
        "transplant": "Mar\u2013Apr",
        "direct_sow": "Feb\u2013Mar (as soon as soil is workable)",
        "harvest": None,
        "bloom": "May\u2013Jul",
        "spacing_in": 6,
        "difficulty": "easy",
        "frost_hardy": True,
        "tip": "Pick flowers daily to encourage more blooms. Provide a trellis or fence to climb. Soak seeds overnight before planting for faster germination.",
        "companions": ["Roses", "Clematis"],
        "avoid_near": [],
    },
    {
        "id": "nasturtiums",
        "name": "Nasturtiums",
        "emoji": "\U0001f9e1",
        "category": "annual",
        "varieties": ["Jewel Mix (compact)", "Alaska (variegated leaves)", "Empress of India (dark red)", "Trailing / Climbing"],
        "pnw_notes": "Edible flowers AND leaves with a peppery kick. Practically indestructible. Thrives in poor soil\u2014too-rich soil produces leaves but few flowers. Great companion plant.",
        "sun": "Full sun to part shade",
        "water": "Moderate\u2014drought tolerant",
        "soil": "Average to poor, well-drained",
        "start_indoors": None,
        "transplant": None,
        "direct_sow": "Apr\u2013May",
        "harvest": None,
        "bloom": "Jun\u2013Oct",
        "spacing_in": 12,
        "difficulty": "easy",
        "frost_hardy": False,
        "tip": "Don\u2019t fertilize\u2014poor soil means more flowers. Leaves and flowers are edible and beautiful in salads. Acts as a trap crop for aphids.",
        "companions": ["Tomatoes", "Squash", "Beans", "Fruit Trees"],
        "avoid_near": [],
    },
]


# ─── Indoor Houseplants for PNW ──────────────────────────────────────────────

HOUSEPLANTS: list[dict] = [
    {
        "id": "monstera-deliciosa",
        "name": "Monstera Deliciosa",
        "emoji": "\U0001f331",
        "category": "houseplant",
        "difficulty": "easy",
        "light": "Bright indirect light",
        "water": "Every 1\u20132 weeks when top 2\" dry",
        "humidity": "40\u201360%",
        "temp": "60\u201385\u00b0F",
        "pnw_notes": "Loves PNW's humid winters. Place near a bright window but out of direct sun. Growth slows Nov\u2013Feb with shorter days.",
        "toxic_pets": True,
        "tip": "Provide a moss pole for larger leaves. Clean leaves monthly\u2014Seattle dust is real.",
    },
    {
        "id": "pothos-golden",
        "name": "Golden Pothos",
        "emoji": "\U0001f33f",
        "category": "houseplant",
        "difficulty": "easy",
        "light": "Low to bright indirect",
        "water": "Every 1\u20132 weeks, let dry between",
        "humidity": "Any",
        "temp": "60\u201385\u00b0F",
        "pnw_notes": "Perfect for Seattle's dark winter months\u2014one of few plants that thrives in low light. Great for north-facing apartments.",
        "toxic_pets": True,
        "tip": "Trim leggy vines and root cuttings in water for new plants.",
    },
    {
        "id": "snake-plant",
        "name": "Snake Plant",
        "emoji": "\U0001fab4",
        "category": "houseplant",
        "difficulty": "easy",
        "light": "Low to bright\u2014very adaptable",
        "water": "Every 2\u20134 weeks",
        "humidity": "Any",
        "temp": "55\u201385\u00b0F",
        "pnw_notes": "Nearly indestructible. Releases oxygen at night\u2014great for PNW bedrooms. Water less in winter.",
        "toxic_pets": True,
        "tip": "Reduce watering to once monthly in Seattle's dark, cool winters.",
    },
    {
        "id": "fiddle-leaf-fig",
        "name": "Fiddle Leaf Fig",
        "emoji": "\U0001f332",
        "category": "houseplant",
        "difficulty": "hard",
        "light": "Bright indirect, some morning sun",
        "water": "Weekly when top 1\" dry",
        "humidity": "50\u201365%",
        "temp": "60\u201380\u00b0F",
        "pnw_notes": "Challenging in Seattle\u2014needs a bright south-facing window and consistent routine. Consider a grow light Nov\u2013Feb.",
        "toxic_pets": True,
        "tip": "Don't move it. FLFs hate changes. Wipe leaves monthly and rotate quarterly.",
    },
    {
        "id": "ferns",
        "name": "Ferns (Boston, Maidenhair)",
        "emoji": "\U0001f33f",
        "category": "houseplant",
        "difficulty": "moderate",
        "light": "Medium indirect",
        "water": "Keep consistently moist",
        "humidity": "60%+",
        "temp": "55\u201375\u00b0F",
        "pnw_notes": "PNW's naturally humid air helps! Bathrooms are ideal. Seattle's cool temps suit ferns perfectly.",
        "toxic_pets": False,
        "tip": "Native sword ferns grow wild in WA forests\u2014proof that ferns love PNW climate.",
    },
    {
        "id": "peace-lily",
        "name": "Peace Lily",
        "emoji": "\U0001f33c",
        "category": "houseplant",
        "difficulty": "easy",
        "light": "Low to medium indirect",
        "water": "Weekly, droops when thirsty",
        "humidity": "50%+",
        "temp": "60\u201380\u00b0F",
        "pnw_notes": "Excellent for Seattle's overcast days. Filters indoor air. Blooms white flowers even in low light.",
        "toxic_pets": True,
        "tip": "Use filtered water\u2014Seattle tap water is good but some areas have fluoride that causes brown tips.",
    },
    {
        "id": "pilea",
        "name": "Chinese Money Plant",
        "emoji": "\U0001f4b2",
        "category": "houseplant",
        "difficulty": "easy",
        "light": "Bright indirect",
        "water": "Weekly when top inch dry",
        "humidity": "Average",
        "temp": "55\u201380\u00b0F",
        "pnw_notes": "Produces lots of pups for sharing\u2014a favorite at Seattle plant swaps. Rotate for even growth.",
        "toxic_pets": False,
        "tip": "Popular at PNW plant swaps and Facebook Marketplace. Share the babies!",
    },
    {
        "id": "calathea",
        "name": "Calathea / Prayer Plant",
        "emoji": "\U0001f3a8",
        "category": "houseplant",
        "difficulty": "hard",
        "light": "Medium indirect, no direct sun",
        "water": "Keep lightly moist, filtered water only",
        "humidity": "60%+",
        "temp": "62\u201380\u00b0F",
        "pnw_notes": "PNW humidity helps but winter heating dries air\u2014use a humidifier. Stunning leaf patterns worth the effort.",
        "toxic_pets": False,
        "tip": "Group with other humidity-loving plants to create a microclimate.",
    },
]


# ─── PNW Yard & Garden Suggestions ──────────────────────────────────────────

YARD_SUGGESTIONS: list[dict] = [
    {
        "id": "native-garden",
        "title": "PNW Native Plant Garden",
        "emoji": "\U0001f33b",
        "description": "Create a low-maintenance garden with native Pacific Northwest plants that support local pollinators and wildlife.",
        "plants": [
            {"name": "Oregon Grape (Mahonia)", "notes": "WA state flower. Evergreen, shade-tolerant, yellow flowers \u2192 blue berries."},
            {"name": "Sword Fern", "notes": "The quintessential PNW understory fern. Thrives in shade."},
            {"name": "Salal", "notes": "Evergreen groundcover. Edible berries. Extremely low-maintenance."},
            {"name": "Red-flowering Currant", "notes": "First native shrub to bloom (Mar). Hummingbird magnet."},
            {"name": "Pacific Madrone", "notes": "Beautiful peeling bark, evergreen broadleaf. Iconic PNW tree."},
            {"name": "Western Red Cedar", "notes": "Evergreen screen/hedge. Sacred to Coast Salish peoples."},
            {"name": "Nootka Rose", "notes": "Native wild rose. Pink flowers, rose hips for tea."},
        ],
        "benefits": ["Low water once established", "Supports native bees & butterflies", "Year-round interest", "No fertilizer needed"],
        "tip": "Shop at local native plant sales (WA Native Plant Society) for best prices and locally-sourced genetics.",
    },
    {
        "id": "rain-garden",
        "title": "Rain Garden",
        "emoji": "\U0001f327\ufe0f",
        "description": "Manage Seattle's abundant rainfall naturally. A rain garden captures runoff from roofs/driveways, filtering pollutants before they reach Puget Sound.",
        "plants": [
            {"name": "Red Twig Dogwood", "notes": "Stunning red branches in winter. Tolerates wet feet."},
            {"name": "Blue Flag Iris", "notes": "Moisture-loving perennial. Purple flowers spring/summer."},
            {"name": "Sedges (Carex)", "notes": "Native grass-like plants. Perfect for rain garden edges."},
            {"name": "Joe Pye Weed", "notes": "Tall, late-summer blooms. Butterfly favorite."},
            {"name": "Rush (Juncus)", "notes": "Tolerates standing water. Great for center of rain garden."},
        ],
        "benefits": ["Reduces stormwater runoff 30\u201399%", "Filters pollutants naturally", "Seattle offers rebates", "Attracts dragonflies & pollinators"],
        "tip": "Seattle Public Utilities offers free rain garden coaching and up to $4.50/sq ft in rebates through RainWise.",
    },
    {
        "id": "edible-landscape",
        "title": "Edible Landscaping",
        "emoji": "\U0001f34e",
        "description": "Replace ornamental plants with beautiful edibles. Seattle's mild climate supports an incredible range of edible perennials.",
        "plants": [
            {"name": "Blueberry Hedge", "notes": "Replace boxwood with blueberries\u2014fall color + fruit!"},
            {"name": "Espaliered Apple/Pear", "notes": "Flat-trained fruit trees along fences. Space-efficient."},
            {"name": "Kiwi Vine (Hardy)", "notes": "Covers arbors. Grape-sized fuzzy fruits."},
            {"name": "Herb Border", "notes": "Rosemary, thyme, lavender\u2014fragrant, evergreen, edible."},
            {"name": "Rhubarb", "notes": "Dramatic ornamental leaves + spring harvest. Perennial."},
            {"name": "Fig Tree (Desert King)", "notes": "Seattle-hardy variety. Plant against south wall."},
        ],
        "benefits": ["Free food from your yard!", "More interesting than lawn", "Lower maintenance than grass", "Teaches kids where food comes from"],
        "tip": "Join Seattle's City Fruit for free fruit tree pruning workshops and to connect with other urban orchardists.",
    },
    {
        "id": "pollinator-garden",
        "title": "Pollinator Garden",
        "emoji": "\U0001f41d",
        "description": "Support bees, butterflies, and hummingbirds with a sequence of blooms from February through October.",
        "plants": [
            {"name": "Crocus (Feb\u2013Mar)", "notes": "First food for emerging bumblebees."},
            {"name": "Lavender (Jun\u2013Aug)", "notes": "Bee paradise. English types hardiest in PNW."},
            {"name": "Echinacea (Jul\u2013Sep)", "notes": "Butterflies and seed-eating birds love it."},
            {"name": "Aster (Sep\u2013Oct)", "notes": "Critical late-season nectar source."},
            {"name": "Red Hot Poker (Jul\u2013Sep)", "notes": "Hummingbird magnet. Striking orange spikes."},
            {"name": "Bee Balm (Jul\u2013Aug)", "notes": "Attracts both bees and hummingbirds."},
        ],
        "benefits": ["Supports declining pollinator populations", "Beautiful successive blooms", "Many are perennial (plant once)", "Helps your veggie garden via pollination"],
        "tip": "Leave some bare soil patches\u201470% of native bee species are ground-nesters and need exposed earth.",
    },
    {
        "id": "raised-beds",
        "title": "Raised Bed Vegetable Garden",
        "emoji": "\U0001f3d7\ufe0f",
        "description": "Raised beds solve Seattle's common soil issues (clay, poor drainage) and warm up earlier in spring for a longer growing season.",
        "plants": [
            {"name": "Spring: Peas, Lettuce, Radishes", "notes": "Start as early as February in raised beds."},
            {"name": "Summer: Tomatoes, Beans, Squash", "notes": "Warm soil = better warm-crop yields."},
            {"name": "Fall: Kale, Beets, Carrots", "notes": "Extend the season with row cover."},
            {"name": "Winter: Garlic, Overwintering Onions", "notes": "Soil stays workable in raised beds."},
        ],
        "benefits": ["Better drainage than Seattle clay", "Soil warms 2\u20133 weeks earlier", "Easier on knees and backs", "Better pest control"],
        "tip": "Use untreated cedar (PNW native wood, rot-resistant). Fill with 60% topsoil + 30% compost + 10% pumice. Seattle's Cedar Grove compost is excellent.",
    },
    {
        "id": "japanese-garden",
        "title": "PNW Japanese-Inspired Garden",
        "emoji": "\U0001f3ef",
        "description": "Seattle's climate is remarkably similar to Japan's. Many traditional Japanese garden plants thrive here naturally.",
        "plants": [
            {"name": "Japanese Maple (Acer palmatum)", "notes": "Hundreds of varieties. Stunning fall color."},
            {"name": "Azaleas & Rhododendrons", "notes": "WA state flower (rhodo). Acidic PNW soil = perfect."},
            {"name": "Bamboo (Clumping varieties)", "notes": "Fargesia types are non-invasive. Avoid running bamboo!"},
            {"name": "Moss", "notes": "Grows naturally in PNW shade. Embrace it instead of fighting it."},
            {"name": "Japanese Forest Grass", "notes": "Golden cascading grass. Elegant in shade."},
            {"name": "Camellia", "notes": "Winter blooms when nothing else flowers. Evergreen."},
        ],
        "benefits": ["Naturally suited to PNW climate", "Year-round visual interest", "Peaceful, meditative spaces", "Low maintenance once established"],
        "tip": "Visit the Seattle Japanese Garden in the Arboretum for inspiration\u2014it's one of the finest outside Japan.",
    },
]


# ─── Seattle Planting Calendar (Zone 8b) ────────────────────────────────────

PLANTING_CALENDAR: list[dict] = [
    {"month": "January", "emoji": "\u2744\ufe0f", "tasks": [
        "Plan your garden\u2014order seeds from Territorial Seed Co (Cottage Grove, OR) or Uprising Seeds (Bellingham, WA)",
        "Prune dormant fruit trees and roses on dry days",
        "Start onion seeds indoors under grow lights",
        "Clean and sharpen tools\u2014oil wooden handles",
        "Check on overwintering perennials under mulch",
        "Browse nursery catalogs for spring-blooming shrubs and trees",
        "Bring in potted rosemary and bay laurel if hard freeze is forecast",
        "Force branches of forsythia, quince, or cherry indoors for early blooms",
        "Test soil pH\u2014PNW soil tends acidic, great for blueberries and rhododendrons",
    ]},
    {"month": "February", "emoji": "\U0001f331", "tasks": [
        "Direct sow: peas, fava beans, spinach, radishes (if soil is workable)",
        "Start indoors: tomatoes, peppers, eggplant under grow lights",
        "Prune blueberries, grapes, and ornamental grasses before new growth",
        "Apply dormant spray to fruit trees for pest and disease prevention",
        "Top-dress beds with compost\u2014Cedar Grove compost is excellent locally",
        "Start sweet pea seeds indoors (soak overnight first for faster germination)",
        "Prune hydrangeas\u2014remove dead wood only on mopheads (buds set on old wood)",
        "Cut back ornamental grasses to 4\u20136 inches before new shoots emerge",
        "Divide and transplant snowdrops and hellebores while in bloom",
    ]},
    {"month": "March", "emoji": "\U0001f337", "tasks": [
        "Direct sow: lettuce, carrots, beets, chard, kale, potatoes, radishes",
        "Transplant: broccoli, cabbage, cauliflower starts outdoors",
        "Start basil, cucumbers, and squash seeds indoors",
        "Divide overgrown perennials: hostas, daylilies, echinacea, ornamental grasses",
        "Plant bare-root fruit trees, berries, and roses\u2014last chance before they leaf out",
        "Start dahlia tubers in pots indoors for a head start on the season",
        "Plant or transplant shrubs: rhododendrons, hydrangeas, lilacs, camellias",
        "Cut back lavender to just above woody growth\u2014never cut into old wood",
        "Enjoy early blooms: crocus, daffodils, cherry blossoms at UW Quad",
    ]},
    {"month": "April", "emoji": "\U0001f327\ufe0f", "tasks": [
        "Transplant tomato and pepper starts (after mid-month, with Wall-o-Water protection)",
        "Direct sow: beans (after soil reaches 60\u00b0F), more lettuce and greens",
        "Start squash and cucumber seeds indoors for May transplanting",
        "Plant strawberries\u2014Hood variety for PNW flavor",
        "Apply organic slug bait (iron phosphate)\u2014slugs are a PNW reality",
        "Plant out perennials: echinacea, hostas, peonies, heather",
        "Transplant sweet pea starts to the garden with trellis support",
        "Fertilize rhododendrons and camellias after they finish blooming",
        "Deadhead daffodils but leave foliage to die back naturally (feeds the bulb)",
    ]},
    {"month": "May", "emoji": "\u2600\ufe0f", "tasks": [
        "After last frost (~May 10): transplant tomatoes, peppers, squash, basil outdoors",
        "Direct sow: beans, corn, cucumbers, summer squash, sunflowers",
        "Mulch everything 2\u20133 inches deep to conserve moisture for summer",
        "Set up drip irrigation if possible\u2014you\u2019ll need it Jul\u2013Sep",
        "Harden off all remaining seedlings before transplanting",
        "Plant dahlia tubers and nasturtium seeds outdoors after last frost",
        "Direct sow annual flowers: nasturtiums, sunflowers, cosmos, zinnias",
        "Pinch back chrysanthemums for bushy growth and more fall blooms",
        "Attend Tilth Alliance\u2019s Edible Plant Sale\u2014Seattle\u2019s biggest plant event!",
    ]},
    {"month": "June", "emoji": "\U0001f33b", "tasks": [
        "Succession plant: lettuce, beans, beets every 2\u20133 weeks",
        "Harvest: peas, lettuce, radishes, strawberries, herbs",
        "Side-dress tomatoes with compost or fish emulsion every 2 weeks",
        "Stake and cage tomatoes before they flop\u2014use sturdy supports",
        "Watch for aphids\u2014blast with water hose or introduce ladybugs",
        "Deadhead roses, lavender, and other perennials to encourage reblooming",
        "Prune spring-flowering shrubs (lilac, rhododendron) immediately after bloom",
        "Begin deep watering schedule\u2014Seattle\u2019s dry season starts now",
        "Enjoy peak blooms: lavender, peonies, sweet peas, rhododendrons",
    ]},
    {"month": "July", "emoji": "\U0001f345", "tasks": [
        "Harvest: first tomatoes, beans, zucchini, blueberries, cucumbers, raspberries",
        "Plant fall crops: kale, broccoli, Brussels sprouts, cabbage starts",
        "Direct sow: fall beets, carrots, lettuce, spinach for autumn harvest",
        "Water consistently 1\u20132 inches/week\u2014Seattle\u2019s dry summers surprise newcomers!",
        "Harvest garlic when lower 3\u20134 leaves brown\u2014cure in shade for 2\u20134 weeks",
        "Stake and tie dahlias as they grow tall\u2014feed every 2 weeks with bloom fertilizer",
        "Deadhead annuals and perennials regularly for continuous summer blooms",
        "Take semi-hardwood cuttings of hydrangeas and lavender to propagate",
        "Watch for powdery mildew on roses and squash\u2014improve air circulation",
    ]},
    {"month": "August", "emoji": "\U0001f33e", "tasks": [
        "Peak harvest: tomatoes, squash, beans, corn, berries, peppers, cucumbers",
        "Direct sow overwintering crops: kale, spinach, chard, winter lettuce",
        "Plant fall lettuce in succession every 2 weeks through mid-month",
        "Start saving seeds from best-performing heirloom varieties",
        "Enjoy the bounty! Preserve excess by canning, freezing, dehydrating, or sharing",
        "Divide and transplant bearded iris (every 3\u20134 years for best bloom)",
        "Order spring-blooming bulbs (tulips, daffodils, alliums) for October planting",
        "Cut and dry lavender stems and hydrangea blooms for indoor arrangements",
        "Continue deep watering trees and shrubs\u2014they need it most during dry August",
    ]},
    {"month": "September", "emoji": "\U0001f342", "tasks": [
        "Harvest winter squash when stems are dry and corky\u2014cure in sun 10\u201314 days",
        "Plant garlic cloves (mid-Sep through Oct\u2014top priority for PNW fall gardening)",
        "Sow cover crops (crimson clover, winter rye, fava beans) in empty beds",
        "Transplant fall starts: overwintering broccoli, cauliflower, Brussels sprouts",
        "Begin putting the edible garden to bed\u2014pull spent plants, add to compost",
        "Plant trees, shrubs, and perennials\u2014fall is the #1 planting season in PNW!",
        "Divide hostas, daylilies, echinacea, and other overgrown perennials",
        "Dig up dahlia tubers after first frost blackens foliage\u2014store in cool, dark place",
        "Overseed or repair bare lawn patches\u2014fall rain will do the watering for you",
    ]},
    {"month": "October", "emoji": "\U0001f383", "tasks": [
        "Plant garlic cloves pointy-end up, 2\u2033 deep, 6\u2033 apart (top fall priority!)",
        "Plant spring-blooming bulbs: tulips, daffodils, crocus, alliums, hyacinths",
        "Mulch overwintering crops and perennials heavily with 3\u20134 inches of leaves or straw",
        "Clean up fallen leaves\u2014compost, make leaf mold, or use as mulch",
        "Plant trees, shrubs, and perennials\u2014roots establish over winter while tops rest",
        "Move tender potted plants (figs, citrus) to sheltered spots or indoors",
        "Cut back finished perennials but leave ornamental grasses for winter interest",
        "Prepare rain garden plants for the wet season\u2014clean debris from swales",
        "Plant allium bulbs for dramatic spring globes\u2014pair with peonies for stunning combos",
    ]},
    {"month": "November", "emoji": "\U0001f343", "tasks": [
        "Harvest: kale, chard, leeks, Brussels sprouts (sweeter after frost!)",
        "Protect tender plants with row cover, cold frames, or cloches",
        "Rake and compost leaves\u2014or shred and use as mulch on beds",
        "Clean and oil tools, drain hoses, winterize irrigation systems",
        "Order seed catalogs and start planning next year\u2019s garden layout",
        "Enjoy late fall color: Japanese maples are at their spectacular peak now",
        "Wrap young fig trees and tender shrubs with burlap for winter protection",
        "Plant bare-root roses\u2014available from nurseries now through March",
        "Check stored dahlia tubers monthly\u2014mist if shriveling, discard any that rot",
    ]},
    {"month": "December", "emoji": "\U0001f384", "tasks": [
        "Harvest overwintered greens (kale, chard, spinach) as needed for fresh meals",
        "Plan next year\u2019s garden layout\u2014rotate crops, sketch beds, dream big",
        "Browse seed catalogs: Territorial, Uprising, Adaptive Seeds, Nichols Garden Nursery",
        "Give gardening gifts: seeds, quality tools, garden journal, nursery gift cards",
        "Enjoy winter blooms: camellias, winter heather, witch hazel, hellebores",
        "Force paperwhite narcissus and amaryllis bulbs indoors for holiday color",
        "Protect outdoor containers from cracking\u2014move glazed pots under cover",
        "Walk the garden and note changes needed\u2014dormant season reveals the garden\u2019s bones",
        "Rest, compost, and reflect\u2014the garden is sleeping but planning never stops",
    ]},
]


# ─── Useful Resources ────────────────────────────────────────────────────────

RESOURCES: list[dict] = [
    {"name": "Territorial Seed Company", "url": "https://territorialseed.com", "desc": "PNW-focused seed company based in Oregon. Varieties selected for our climate."},
    {"name": "Uprising Seeds", "url": "https://uprisingorganics.com", "desc": "Organic seeds from Bellingham, WA. Open-pollinated varieties bred for PNW."},
    {"name": "Swansons Nursery", "url": "https://swansonsnursery.com", "desc": "Seattle institution since 1924. Expert staff and PNW-adapted plants."},
    {"name": "Seattle Tilth Alliance", "url": "https://tilthalliance.org", "desc": "Community gardens, classes, and the annual Edible Plant Sale (May)."},
    {"name": "WSU Extension \u2013 King County", "url": "https://extension.wsu.edu/king/", "desc": "Free research-based gardening advice. Master Gardener hotline."},
    {"name": "RainWise (Seattle)", "url": "https://700milliongallons.org", "desc": "Rebates for rain gardens and cisterns. Up to $4.50/sq ft."},
    {"name": "City Fruit", "url": "https://cityfruit.org", "desc": "Urban fruit tree education, pruning workshops, and community harvest."},
    {"name": "WA Native Plant Society", "url": "https://wnps.org", "desc": "Native plant sales, events, and habitat restoration info."},
    {"name": "The Sill", "url": "https://thesill.com", "desc": "Houseplant care guides, articles, and online plant shop."},
    {"name": "Gardenize", "url": "https://gardenize.com", "desc": "Plant diary app. Track watering, fertilizing, and growth photos."},
    {"name": "Seedtime", "url": "https://seedtime.us", "desc": "Free garden planning tool with zone-based planting calendars."},
]


# ─── Search / Filter Helpers ─────────────────────────────────────────────────

ALL_PLANTS = VEGETABLES + HOUSEPLANTS
CATEGORIES = {"vegetable": "Vegetables", "fruit": "Fruit", "herb": "Herbs",
              "perennial": "Perennials", "annual": "Annuals",
              "shrub": "Shrubs & Bushes", "tree": "Trees",
              "houseplant": "Houseplants"}
DIFFICULTIES = ["easy", "moderate", "hard"]

# Wikipedia article names for fetching thumbnail images (client-side)
# and YouTube search queries for growing guides
_MEDIA: dict[str, dict] = {
    "tomato":             {"wiki": "Tomato",               "yt": "how to grow tomatoes seattle pacific northwest"},
    "kale":               {"wiki": "Kale",                 "yt": "how to grow kale pacific northwest year round"},
    "lettuce":            {"wiki": "Lettuce",              "yt": "growing lettuce seattle cool weather"},
    "sugar-snap-peas":    {"wiki": "Snap_pea",             "yt": "growing sugar snap peas pacific northwest"},
    "zucchini":           {"wiki": "Zucchini",             "yt": "how to grow zucchini squash seattle"},
    "garlic":             {"wiki": "Garlic",               "yt": "planting garlic fall pacific northwest"},
    "blueberries":        {"wiki": "Blueberry",            "yt": "growing blueberries pacific northwest acidic soil"},
    "strawberries":       {"wiki": "Strawberry",           "yt": "growing strawberries seattle hood variety"},
    "herbs-basil":        {"wiki": "Basil",                "yt": "growing basil seattle pacific northwest"},
    "herbs-rosemary":     {"wiki": "Rosemary",             "yt": "growing rosemary outdoors pacific northwest"},
    "beans-green":        {"wiki": "Green_bean",           "yt": "growing green beans pole bush pacific northwest"},
    "carrots":            {"wiki": "Carrot",               "yt": "growing carrots pacific northwest raised bed"},
    "potatoes":           {"wiki": "Potato",               "yt": "growing potatoes seattle raised bed container"},
    "beets":              {"wiki": "Beetroot",             "yt": "growing beets pacific northwest garden"},
    "cucumber":           {"wiki": "Cucumber",             "yt": "growing cucumbers seattle pacific northwest"},
    "chard":              {"wiki": "Chard",                "yt": "growing swiss chard pacific northwest"},
    "monstera-deliciosa": {"wiki": "Monstera_deliciosa",   "yt": "monstera deliciosa care indoor plant"},
    "pothos-golden":      {"wiki": "Epipremnum_aureum",    "yt": "golden pothos care tips low light"},
    "snake-plant":        {"wiki": "Dracaena_trifasciata", "yt": "snake plant care beginner houseplant"},
    "fiddle-leaf-fig":    {"wiki": "Ficus_lyrata",         "yt": "fiddle leaf fig care tips indoor"},
    "ferns":              {"wiki": "Nephrolepis_exaltata", "yt": "boston fern care indoor humidity"},
    "peace-lily":         {"wiki": "Spathiphyllum",        "yt": "peace lily care low light indoor plant"},
    "pilea":              {"wiki": "Pilea_peperomioides",   "yt": "pilea peperomioides care propagation"},
    "calathea":           {"wiki": "Goeppertia",           "yt": "calathea prayer plant care humidity"},
    "broccoli":           {"wiki": "Broccoli",             "yt": "how to grow broccoli pacific northwest fall"},
    "spinach":            {"wiki": "Spinach",              "yt": "growing spinach seattle cool weather"},
    "peppers":            {"wiki": "Bell_pepper",          "yt": "growing peppers seattle pacific northwest"},
    "radishes":           {"wiki": "Radish",               "yt": "growing radishes fast easy pacific northwest"},
    "brussels-sprouts":   {"wiki": "Brussels_sprout",      "yt": "growing brussels sprouts pacific northwest winter"},
    "winter-squash":      {"wiki": "Squash_(plant)",       "yt": "growing winter squash pacific northwest storage"},
    "raspberries":        {"wiki": "Raspberry",            "yt": "growing raspberries pacific northwest pruning"},
    "apples":             {"wiki": "Apple",                "yt": "growing apple trees pacific northwest home orchard"},
    "figs":               {"wiki": "Common_fig",           "yt": "growing fig trees seattle pacific northwest"},
    "herbs-cilantro":     {"wiki": "Coriander",            "yt": "growing cilantro slow bolt pacific northwest"},
    "herbs-thyme":        {"wiki": "Thyme",                "yt": "growing thyme perennial herb pacific northwest"},
    "herbs-mint":         {"wiki": "Mentha",               "yt": "growing mint container herb garden"},
    "rhododendron":       {"wiki": "Rhododendron",         "yt": "rhododendron care pacific northwest seattle"},
    "hydrangea":          {"wiki": "Hydrangea",            "yt": "growing hydrangeas pacific northwest blue pink"},
    "lilac":              {"wiki": "Syringa",              "yt": "growing lilacs pacific northwest fragrant shrub"},
    "camellia":           {"wiki": "Camellia",             "yt": "camellia care pacific northwest winter blooming"},
    "japanese-maple":     {"wiki": "Acer_palmatum",        "yt": "japanese maple care pacific northwest seattle"},
    "dogwood":            {"wiki": "Cornus_nuttallii",     "yt": "pacific dogwood tree washington state native"},
    "cherry-ornamental":  {"wiki": "Prunus_serrulata",     "yt": "cherry blossom trees seattle planting care"},
    "lavender":           {"wiki": "Lavandula",            "yt": "growing lavender pacific northwest seattle"},
    "dahlia":             {"wiki": "Dahlia",               "yt": "growing dahlias seattle pacific northwest tubers"},
    "peony":              {"wiki": "Paeonia",              "yt": "growing peonies pacific northwest planting care"},
    "hostas":             {"wiki": "Hosta",                "yt": "growing hostas shade garden pacific northwest"},
    "echinacea":          {"wiki": "Echinacea",            "yt": "growing echinacea coneflower pacific northwest"},
    "heather":            {"wiki": "Calluna",              "yt": "heather heath garden pacific northwest evergreen"},
    "sunflowers":         {"wiki": "Helianthus_annuus",    "yt": "growing sunflowers seattle pacific northwest"},
    "sweet-peas":         {"wiki": "Lathyrus_odoratus",    "yt": "growing sweet peas pacific northwest fragrant"},
    "nasturtiums":        {"wiki": "Tropaeolum",           "yt": "growing nasturtiums edible flowers garden"},
}


def _enrich(plant: dict) -> dict:
    """Add media URLs to a plant dict."""
    pid = plant["id"]
    media = _MEDIA.get(pid, {})
    plant["wiki"] = media.get("wiki", plant["name"].replace(" ", "_"))
    plant["youtube_search"] = media.get("yt", f"how to grow {plant['name']} pacific northwest")
    return plant


# Enrich all plants at import time
for _p in ALL_PLANTS:
    _enrich(_p)


def search_all(query: str = "", category: str = "", difficulty: str = "") -> list[dict]:
    """Search across all plants."""
    results = ALL_PLANTS
    if query:
        q = query.lower()
        results = [
            p for p in results
            if q in p["name"].lower()
            or q in p.get("id", "")
            or any(q in v.lower() for v in p.get("varieties", []))
            or q in p.get("pnw_notes", "").lower()
        ]
    if category:
        results = [p for p in results if p.get("category") == category]
    if difficulty:
        results = [p for p in results if p.get("difficulty") == difficulty]
    return results


def get_plant(plant_id: str) -> dict | None:
    """Get a plant by ID."""
    for p in ALL_PLANTS:
        if p["id"] == plant_id:
            return p
    return None
